// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/mcp/v1/mcp.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Parameters    []*ToolParameter       `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Returns       []*ToolParameter       `protobuf:"bytes,6,rep,name=returns,proto3" json:"returns,omitempty"`
	CostProfile   *CostProfile           `protobuf:"bytes,7,opt,name=cost_profile,json=costProfile,proto3" json:"cost_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *ToolDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ToolDefinition) GetParameters() []*ToolParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ToolDefinition) GetReturns() []*ToolParameter {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *ToolDefinition) GetCostProfile() *CostProfile {
	if x != nil {
		return x.CostProfile
	}
	return nil
}

type ToolParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Default       string                 `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"` // JSON-encoded default value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParameter) Reset() {
	*x = ToolParameter{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParameter) ProtoMessage() {}

func (x *ToolParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParameter.ProtoReflect.Descriptor instead.
func (*ToolParameter) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *ToolParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolParameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ToolParameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type CostProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputeCost   float64                `protobuf:"fixed64,1,opt,name=compute_cost,json=computeCost,proto3" json:"compute_cost,omitempty"`
	MemoryCost    int64                  `protobuf:"varint,2,opt,name=memory_cost,json=memoryCost,proto3" json:"memory_cost,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TokensCost    int64                  `protobuf:"varint,4,opt,name=tokens_cost,json=tokensCost,proto3" json:"tokens_cost,omitempty"`
	ApiCallsCost  int64                  `protobuf:"varint,5,opt,name=api_calls_cost,json=apiCallsCost,proto3" json:"api_calls_cost,omitempty"`
	FinancialCost float64                `protobuf:"fixed64,6,opt,name=financial_cost,json=financialCost,proto3" json:"financial_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostProfile) Reset() {
	*x = CostProfile{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostProfile) ProtoMessage() {}

func (x *CostProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostProfile.ProtoReflect.Descriptor instead.
func (*CostProfile) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *CostProfile) GetComputeCost() float64 {
	if x != nil {
		return x.ComputeCost
	}
	return 0
}

func (x *CostProfile) GetMemoryCost() int64 {
	if x != nil {
		return x.MemoryCost
	}
	return 0
}

func (x *CostProfile) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CostProfile) GetTokensCost() int64 {
	if x != nil {
		return x.TokensCost
	}
	return 0
}

func (x *CostProfile) GetApiCallsCost() int64 {
	if x != nil {
		return x.ApiCallsCost
	}
	return 0
}

func (x *CostProfile) GetFinancialCost() float64 {
	if x != nil {
		return x.FinancialCost
	}
	return 0
}

type ToolRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          *ToolDefinition        `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRegistrationRequest) Reset() {
	*x = ToolRegistrationRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRegistrationRequest) ProtoMessage() {}

func (x *ToolRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ToolRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *ToolRegistrationRequest) GetTool() *ToolDefinition {
	if x != nil {
		return x.Tool
	}
	return nil
}

type ToolRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ToolId        string                 `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRegistrationResponse) Reset() {
	*x = ToolRegistrationResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRegistrationResponse) ProtoMessage() {}

func (x *ToolRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRegistrationResponse.ProtoReflect.Descriptor instead.
func (*ToolRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *ToolRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolRegistrationResponse) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolRegistrationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ToolDeregistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDeregistrationRequest) Reset() {
	*x = ToolDeregistrationRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDeregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDeregistrationRequest) ProtoMessage() {}

func (x *ToolDeregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDeregistrationRequest.ProtoReflect.Descriptor instead.
func (*ToolDeregistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *ToolDeregistrationRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type ToolDeregistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDeregistrationResponse) Reset() {
	*x = ToolDeregistrationResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDeregistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDeregistrationResponse) ProtoMessage() {}

func (x *ToolDeregistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDeregistrationResponse.ProtoReflect.Descriptor instead.
func (*ToolDeregistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *ToolDeregistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolDeregistrationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ToolDiscoveryRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequiredCapabilities []string               `protobuf:"bytes,1,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	MaxCost              float64                `protobuf:"fixed64,2,opt,name=max_cost,json=maxCost,proto3" json:"max_cost,omitempty"`
	MaxLatencyMs         int64                  `protobuf:"varint,3,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	Limit                int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolDiscoveryRequest) Reset() {
	*x = ToolDiscoveryRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDiscoveryRequest) ProtoMessage() {}

func (x *ToolDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*ToolDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *ToolDiscoveryRequest) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *ToolDiscoveryRequest) GetMaxCost() float64 {
	if x != nil {
		return x.MaxCost
	}
	return 0
}

func (x *ToolDiscoveryRequest) GetMaxLatencyMs() int64 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *ToolDiscoveryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ToolDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDiscoveryResponse) Reset() {
	*x = ToolDiscoveryResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDiscoveryResponse) ProtoMessage() {}

func (x *ToolDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*ToolDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{8}
}

func (x *ToolDiscoveryResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Parameters    []byte                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"` // JSON-encoded parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionRequest) Reset() {
	*x = ToolExecutionRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionRequest) ProtoMessage() {}

func (x *ToolExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionRequest.ProtoReflect.Descriptor instead.
func (*ToolExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{9}
}

func (x *ToolExecutionRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ToolExecutionRequest) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                         // JSON-encoded result
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionResponse) Reset() {
	*x = ToolExecutionResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionResponse) ProtoMessage() {}

func (x *ToolExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionResponse.ProtoReflect.Descriptor instead.
func (*ToolExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{10}
}

func (x *ToolExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ToolExecutionResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolExecutionResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ToolExecutionResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ToolHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolHealthRequest) Reset() {
	*x = ToolHealthRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolHealthRequest) ProtoMessage() {}

func (x *ToolHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolHealthRequest.ProtoReflect.Descriptor instead.
func (*ToolHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{11}
}

func (x *ToolHealthRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type ToolHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolHealthResponse) Reset() {
	*x = ToolHealthResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolHealthResponse) ProtoMessage() {}

func (x *ToolHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolHealthResponse.ProtoReflect.Descriptor instead.
func (*ToolHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{12}
}

func (x *ToolHealthResponse) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type CostReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp
	ComputeCost   float64                `protobuf:"fixed64,4,opt,name=compute_cost,json=computeCost,proto3" json:"compute_cost,omitempty"`
	MemoryCost    int64                  `protobuf:"varint,5,opt,name=memory_cost,json=memoryCost,proto3" json:"memory_cost,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TokensCost    int64                  `protobuf:"varint,7,opt,name=tokens_cost,json=tokensCost,proto3" json:"tokens_cost,omitempty"`
	ApiCallsCost  int64                  `protobuf:"varint,8,opt,name=api_calls_cost,json=apiCallsCost,proto3" json:"api_calls_cost,omitempty"`
	FinancialCost float64                `protobuf:"fixed64,9,opt,name=financial_cost,json=financialCost,proto3" json:"financial_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReport) Reset() {
	*x = CostReport{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReport) ProtoMessage() {}

func (x *CostReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReport.ProtoReflect.Descriptor instead.
func (*CostReport) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{13}
}

func (x *CostReport) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CostReport) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CostReport) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CostReport) GetComputeCost() float64 {
	if x != nil {
		return x.ComputeCost
	}
	return 0
}

func (x *CostReport) GetMemoryCost() int64 {
	if x != nil {
		return x.MemoryCost
	}
	return 0
}

func (x *CostReport) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CostReport) GetTokensCost() int64 {
	if x != nil {
		return x.TokensCost
	}
	return 0
}

func (x *CostReport) GetApiCallsCost() int64 {
	if x != nil {
		return x.ApiCallsCost
	}
	return 0
}

func (x *CostReport) GetFinancialCost() float64 {
	if x != nil {
		return x.FinancialCost
	}
	return 0
}

type CostReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *CostReport            `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReportRequest) Reset() {
	*x = CostReportRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReportRequest) ProtoMessage() {}

func (x *CostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReportRequest.ProtoReflect.Descriptor instead.
func (*CostReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{14}
}

func (x *CostReportRequest) GetCost() *CostReport {
	if x != nil {
		return x.Cost
	}
	return nil
}

type CostReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReportResponse) Reset() {
	*x = CostReportResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReportResponse) ProtoMessage() {}

func (x *CostReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReportResponse.ProtoReflect.Descriptor instead.
func (*CostReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{15}
}

func (x *CostReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CostReportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CostQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationIds  []string               `protobuf:"bytes,1,rep,name=operation_ids,json=operationIds,proto3" json:"operation_ids,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp
	GroupBy       string                 `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`        // "operation", "tool", "user"
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostQueryRequest) Reset() {
	*x = CostQueryRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostQueryRequest) ProtoMessage() {}

func (x *CostQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostQueryRequest.ProtoReflect.Descriptor instead.
func (*CostQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{16}
}

func (x *CostQueryRequest) GetOperationIds() []string {
	if x != nil {
		return x.OperationIds
	}
	return nil
}

func (x *CostQueryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CostQueryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CostQueryRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *CostQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CostQueryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalCost       *CostReport            `protobuf:"bytes,1,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	BreakdownBy     string                 `protobuf:"bytes,2,opt,name=breakdown_by,json=breakdownBy,proto3" json:"breakdown_by,omitempty"`
	Breakdown       []*CostReport          `protobuf:"bytes,3,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	Recommendations []string               `protobuf:"bytes,4,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CostQueryResponse) Reset() {
	*x = CostQueryResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostQueryResponse) ProtoMessage() {}

func (x *CostQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostQueryResponse.ProtoReflect.Descriptor instead.
func (*CostQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{17}
}

func (x *CostQueryResponse) GetTotalCost() *CostReport {
	if x != nil {
		return x.TotalCost
	}
	return nil
}

func (x *CostQueryResponse) GetBreakdownBy() string {
	if x != nil {
		return x.BreakdownBy
	}
	return ""
}

func (x *CostQueryResponse) GetBreakdown() []*CostReport {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *CostQueryResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{18}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{19}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{20}
}

type SystemFeatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tls           bool                   `protobuf:"varint,1,opt,name=tls,proto3" json:"tls,omitempty"`
	Auth          bool                   `protobuf:"varint,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Metrics       bool                   `protobuf:"varint,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Tracing       bool                   `protobuf:"varint,4,opt,name=tracing,proto3" json:"tracing,omitempty"`
	CostTracking  bool                   `protobuf:"varint,5,opt,name=cost_tracking,json=costTracking,proto3" json:"cost_tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemFeatures) Reset() {
	*x = SystemFeatures{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemFeatures) ProtoMessage() {}

func (x *SystemFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemFeatures.ProtoReflect.Descriptor instead.
func (*SystemFeatures) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{21}
}

func (x *SystemFeatures) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *SystemFeatures) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *SystemFeatures) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *SystemFeatures) GetTracing() bool {
	if x != nil {
		return x.Tracing
	}
	return false
}

func (x *SystemFeatures) GetCostTracking() bool {
	if x != nil {
		return x.CostTracking
	}
	return false
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Features      *SystemFeatures        `protobuf:"bytes,4,opt,name=features,proto3" json:"features,omitempty"`
	ToolsCount    int64                  `protobuf:"varint,5,opt,name=tools_count,json=toolsCount,proto3" json:"tools_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_v1_mcp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_v1_mcp_proto_rawDescGZIP(), []int{22}
}

func (x *SystemInfoResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SystemInfoResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *SystemInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfoResponse) GetFeatures() *SystemFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *SystemInfoResponse) GetToolsCount() int64 {
	if x != nil {
		return x.ToolsCount
	}
	return 0
}

var File_proto_mcp_v1_mcp_proto protoreflect.FileDescriptor

const file_proto_mcp_v1_mcp_proto_rawDesc = "" +
	"\n" +
	"\x16proto/mcp/v1/mcp.proto\x12\x06mcp.v1\"\x9a\x02\n" +
	"\x0eToolDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x125\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x15.mcp.v1.ToolParameterR\n" +
	"parameters\x12/\n" +
	"\areturns\x18\x06 \x03(\v2\x15.mcp.v1.ToolParameterR\areturns\x126\n" +
	"\fcost_profile\x18\a \x01(\v2\x13.mcp.v1.CostProfileR\vcostProfile\"\x8f\x01\n" +
	"\rToolParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x18\n" +
	"\adefault\x18\x05 \x01(\tR\adefault\"\xde\x01\n" +
	"\vCostProfile\x12!\n" +
	"\fcompute_cost\x18\x01 \x01(\x01R\vcomputeCost\x12\x1f\n" +
	"\vmemory_cost\x18\x02 \x01(\x03R\n" +
	"memoryCost\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x1f\n" +
	"\vtokens_cost\x18\x04 \x01(\x03R\n" +
	"tokensCost\x12$\n" +
	"\x0eapi_calls_cost\x18\x05 \x01(\x03R\fapiCallsCost\x12%\n" +
	"\x0efinancial_cost\x18\x06 \x01(\x01R\rfinancialCost\"E\n" +
	"\x17ToolRegistrationRequest\x12*\n" +
	"\x04tool\x18\x01 \x01(\v2\x16.mcp.v1.ToolDefinitionR\x04tool\"r\n" +
	"\x18ToolRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atool_id\x18\x02 \x01(\tR\x06toolId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"4\n" +
	"\x19ToolDeregistrationRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"[\n" +
	"\x1aToolDeregistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa2\x01\n" +
	"\x14ToolDiscoveryRequest\x123\n" +
	"\x15required_capabilities\x18\x01 \x03(\tR\x14requiredCapabilities\x12\x19\n" +
	"\bmax_cost\x18\x02 \x01(\x01R\amaxCost\x12$\n" +
	"\x0emax_latency_ms\x18\x03 \x01(\x03R\fmaxLatencyMs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"E\n" +
	"\x15ToolDiscoveryResponse\x12,\n" +
	"\x05tools\x18\x01 \x03(\v2\x16.mcp.v1.ToolDefinitionR\x05tools\"r\n" +
	"\x14ToolExecutionRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\fR\n" +
	"parameters\"\x8c\x01\n" +
	"\x15ToolExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\",\n" +
	"\x11ToolHealthRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"G\n" +
	"\x12ToolHealthResponse\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\"\xba\x02\n" +
	"\n" +
	"CostReport\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12!\n" +
	"\fcompute_cost\x18\x04 \x01(\x01R\vcomputeCost\x12\x1f\n" +
	"\vmemory_cost\x18\x05 \x01(\x03R\n" +
	"memoryCost\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12\x1f\n" +
	"\vtokens_cost\x18\a \x01(\x03R\n" +
	"tokensCost\x12$\n" +
	"\x0eapi_calls_cost\x18\b \x01(\x03R\fapiCallsCost\x12%\n" +
	"\x0efinancial_cost\x18\t \x01(\x01R\rfinancialCost\";\n" +
	"\x11CostReportRequest\x12&\n" +
	"\x04cost\x18\x01 \x01(\v2\x12.mcp.v1.CostReportR\x04cost\"S\n" +
	"\x12CostReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa2\x01\n" +
	"\x10CostQueryRequest\x12#\n" +
	"\roperation_ids\x18\x01 \x03(\tR\foperationIds\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x19\n" +
	"\bgroup_by\x18\x04 \x01(\tR\agroupBy\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xc5\x01\n" +
	"\x11CostQueryResponse\x121\n" +
	"\n" +
	"total_cost\x18\x01 \x01(\v2\x12.mcp.v1.CostReportR\ttotalCost\x12!\n" +
	"\fbreakdown_by\x18\x02 \x01(\tR\vbreakdownBy\x120\n" +
	"\tbreakdown\x18\x03 \x03(\v2\x12.mcp.v1.CostReportR\tbreakdown\x12(\n" +
	"\x0frecommendations\x18\x04 \x03(\tR\x0frecommendations\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"I\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\x13\n" +
	"\x11SystemInfoRequest\"\x8f\x01\n" +
	"\x0eSystemFeatures\x12\x10\n" +
	"\x03tls\x18\x01 \x01(\bR\x03tls\x12\x12\n" +
	"\x04auth\x18\x02 \x01(\bR\x04auth\x12\x18\n" +
	"\ametrics\x18\x03 \x01(\bR\ametrics\x12\x18\n" +
	"\atracing\x18\x04 \x01(\bR\atracing\x12#\n" +
	"\rcost_tracking\x18\x05 \x01(\bR\fcostTracking\"\xc1\x01\n" +
	"\x12SystemInfoResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x122\n" +
	"\bfeatures\x18\x04 \x01(\v2\x16.mcp.v1.SystemFeaturesR\bfeatures\x12\x1f\n" +
	"\vtools_count\x18\x05 \x01(\x03R\n" +
	"toolsCount2\x9f\x05\n" +
	"\n" +
	"MCPService\x12Q\n" +
	"\fRegisterTool\x12\x1f.mcp.v1.ToolRegistrationRequest\x1a .mcp.v1.ToolRegistrationResponse\x12W\n" +
	"\x0eDeregisterTool\x12!.mcp.v1.ToolDeregistrationRequest\x1a\".mcp.v1.ToolDeregistrationResponse\x12L\n" +
	"\rDiscoverTools\x12\x1c.mcp.v1.ToolDiscoveryRequest\x1a\x1d.mcp.v1.ToolDiscoveryResponse\x12J\n" +
	"\vExecuteTool\x12\x1c.mcp.v1.ToolExecutionRequest\x1a\x1d.mcp.v1.ToolExecutionResponse\x12H\n" +
	"\x0fCheckToolHealth\x12\x19.mcp.v1.ToolHealthRequest\x1a\x1a.mcp.v1.ToolHealthResponse\x12C\n" +
	"\n" +
	"ReportCost\x12\x19.mcp.v1.CostReportRequest\x1a\x1a.mcp.v1.CostReportResponse\x12A\n" +
	"\n" +
	"QueryCosts\x12\x18.mcp.v1.CostQueryRequest\x1a\x19.mcp.v1.CostQueryResponse\x121\n" +
	"\x04Ping\x12\x13.mcp.v1.PingRequest\x1a\x14.mcp.v1.PingResponse\x12F\n" +
	"\rGetSystemInfo\x12\x19.mcp.v1.SystemInfoRequest\x1a\x1a.mcp.v1.SystemInfoResponseB3Z1github.com/guild-ventures/guild-core/pkg/mcp/grpcb\x06proto3"

var (
	file_proto_mcp_v1_mcp_proto_rawDescOnce sync.Once
	file_proto_mcp_v1_mcp_proto_rawDescData []byte
)

func file_proto_mcp_v1_mcp_proto_rawDescGZIP() []byte {
	file_proto_mcp_v1_mcp_proto_rawDescOnce.Do(func() {
		file_proto_mcp_v1_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcp_v1_mcp_proto_rawDesc), len(file_proto_mcp_v1_mcp_proto_rawDesc)))
	})
	return file_proto_mcp_v1_mcp_proto_rawDescData
}

var file_proto_mcp_v1_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_mcp_v1_mcp_proto_goTypes = []any{
	(*ToolDefinition)(nil),             // 0: mcp.v1.ToolDefinition
	(*ToolParameter)(nil),              // 1: mcp.v1.ToolParameter
	(*CostProfile)(nil),                // 2: mcp.v1.CostProfile
	(*ToolRegistrationRequest)(nil),    // 3: mcp.v1.ToolRegistrationRequest
	(*ToolRegistrationResponse)(nil),   // 4: mcp.v1.ToolRegistrationResponse
	(*ToolDeregistrationRequest)(nil),  // 5: mcp.v1.ToolDeregistrationRequest
	(*ToolDeregistrationResponse)(nil), // 6: mcp.v1.ToolDeregistrationResponse
	(*ToolDiscoveryRequest)(nil),       // 7: mcp.v1.ToolDiscoveryRequest
	(*ToolDiscoveryResponse)(nil),      // 8: mcp.v1.ToolDiscoveryResponse
	(*ToolExecutionRequest)(nil),       // 9: mcp.v1.ToolExecutionRequest
	(*ToolExecutionResponse)(nil),      // 10: mcp.v1.ToolExecutionResponse
	(*ToolHealthRequest)(nil),          // 11: mcp.v1.ToolHealthRequest
	(*ToolHealthResponse)(nil),         // 12: mcp.v1.ToolHealthResponse
	(*CostReport)(nil),                 // 13: mcp.v1.CostReport
	(*CostReportRequest)(nil),          // 14: mcp.v1.CostReportRequest
	(*CostReportResponse)(nil),         // 15: mcp.v1.CostReportResponse
	(*CostQueryRequest)(nil),           // 16: mcp.v1.CostQueryRequest
	(*CostQueryResponse)(nil),          // 17: mcp.v1.CostQueryResponse
	(*PingRequest)(nil),                // 18: mcp.v1.PingRequest
	(*PingResponse)(nil),               // 19: mcp.v1.PingResponse
	(*SystemInfoRequest)(nil),          // 20: mcp.v1.SystemInfoRequest
	(*SystemFeatures)(nil),             // 21: mcp.v1.SystemFeatures
	(*SystemInfoResponse)(nil),         // 22: mcp.v1.SystemInfoResponse
}
var file_proto_mcp_v1_mcp_proto_depIdxs = []int32{
	1,  // 0: mcp.v1.ToolDefinition.parameters:type_name -> mcp.v1.ToolParameter
	1,  // 1: mcp.v1.ToolDefinition.returns:type_name -> mcp.v1.ToolParameter
	2,  // 2: mcp.v1.ToolDefinition.cost_profile:type_name -> mcp.v1.CostProfile
	0,  // 3: mcp.v1.ToolRegistrationRequest.tool:type_name -> mcp.v1.ToolDefinition
	0,  // 4: mcp.v1.ToolDiscoveryResponse.tools:type_name -> mcp.v1.ToolDefinition
	13, // 5: mcp.v1.CostReportRequest.cost:type_name -> mcp.v1.CostReport
	13, // 6: mcp.v1.CostQueryResponse.total_cost:type_name -> mcp.v1.CostReport
	13, // 7: mcp.v1.CostQueryResponse.breakdown:type_name -> mcp.v1.CostReport
	21, // 8: mcp.v1.SystemInfoResponse.features:type_name -> mcp.v1.SystemFeatures
	3,  // 9: mcp.v1.MCPService.RegisterTool:input_type -> mcp.v1.ToolRegistrationRequest
	5,  // 10: mcp.v1.MCPService.DeregisterTool:input_type -> mcp.v1.ToolDeregistrationRequest
	7,  // 11: mcp.v1.MCPService.DiscoverTools:input_type -> mcp.v1.ToolDiscoveryRequest
	9,  // 12: mcp.v1.MCPService.ExecuteTool:input_type -> mcp.v1.ToolExecutionRequest
	11, // 13: mcp.v1.MCPService.CheckToolHealth:input_type -> mcp.v1.ToolHealthRequest
	14, // 14: mcp.v1.MCPService.ReportCost:input_type -> mcp.v1.CostReportRequest
	16, // 15: mcp.v1.MCPService.QueryCosts:input_type -> mcp.v1.CostQueryRequest
	18, // 16: mcp.v1.MCPService.Ping:input_type -> mcp.v1.PingRequest
	20, // 17: mcp.v1.MCPService.GetSystemInfo:input_type -> mcp.v1.SystemInfoRequest
	4,  // 18: mcp.v1.MCPService.RegisterTool:output_type -> mcp.v1.ToolRegistrationResponse
	6,  // 19: mcp.v1.MCPService.DeregisterTool:output_type -> mcp.v1.ToolDeregistrationResponse
	8,  // 20: mcp.v1.MCPService.DiscoverTools:output_type -> mcp.v1.ToolDiscoveryResponse
	10, // 21: mcp.v1.MCPService.ExecuteTool:output_type -> mcp.v1.ToolExecutionResponse
	12, // 22: mcp.v1.MCPService.CheckToolHealth:output_type -> mcp.v1.ToolHealthResponse
	15, // 23: mcp.v1.MCPService.ReportCost:output_type -> mcp.v1.CostReportResponse
	17, // 24: mcp.v1.MCPService.QueryCosts:output_type -> mcp.v1.CostQueryResponse
	19, // 25: mcp.v1.MCPService.Ping:output_type -> mcp.v1.PingResponse
	22, // 26: mcp.v1.MCPService.GetSystemInfo:output_type -> mcp.v1.SystemInfoResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_mcp_v1_mcp_proto_init() }
func file_proto_mcp_v1_mcp_proto_init() {
	if File_proto_mcp_v1_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcp_v1_mcp_proto_rawDesc), len(file_proto_mcp_v1_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mcp_v1_mcp_proto_goTypes,
		DependencyIndexes: file_proto_mcp_v1_mcp_proto_depIdxs,
		MessageInfos:      file_proto_mcp_v1_mcp_proto_msgTypes,
	}.Build()
	File_proto_mcp_v1_mcp_proto = out.File
	file_proto_mcp_v1_mcp_proto_goTypes = nil
	file_proto_mcp_v1_mcp_proto_depIdxs = nil
}
