// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/mcp/v1/mcp.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCPService_RegisterTool_FullMethodName    = "/mcp.v1.MCPService/RegisterTool"
	MCPService_DeregisterTool_FullMethodName  = "/mcp.v1.MCPService/DeregisterTool"
	MCPService_DiscoverTools_FullMethodName   = "/mcp.v1.MCPService/DiscoverTools"
	MCPService_ExecuteTool_FullMethodName     = "/mcp.v1.MCPService/ExecuteTool"
	MCPService_CheckToolHealth_FullMethodName = "/mcp.v1.MCPService/CheckToolHealth"
	MCPService_ReportCost_FullMethodName      = "/mcp.v1.MCPService/ReportCost"
	MCPService_QueryCosts_FullMethodName      = "/mcp.v1.MCPService/QueryCosts"
	MCPService_Ping_FullMethodName            = "/mcp.v1.MCPService/Ping"
	MCPService_GetSystemInfo_FullMethodName   = "/mcp.v1.MCPService/GetSystemInfo"
)

// MCPServiceClient is the client API for MCPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCPService provides gRPC interface for Meta-Coordination Protocol
type MCPServiceClient interface {
	// Tool management
	RegisterTool(ctx context.Context, in *ToolRegistrationRequest, opts ...grpc.CallOption) (*ToolRegistrationResponse, error)
	DeregisterTool(ctx context.Context, in *ToolDeregistrationRequest, opts ...grpc.CallOption) (*ToolDeregistrationResponse, error)
	DiscoverTools(ctx context.Context, in *ToolDiscoveryRequest, opts ...grpc.CallOption) (*ToolDiscoveryResponse, error)
	ExecuteTool(ctx context.Context, in *ToolExecutionRequest, opts ...grpc.CallOption) (*ToolExecutionResponse, error)
	CheckToolHealth(ctx context.Context, in *ToolHealthRequest, opts ...grpc.CallOption) (*ToolHealthResponse, error)
	// Cost tracking
	ReportCost(ctx context.Context, in *CostReportRequest, opts ...grpc.CallOption) (*CostReportResponse, error)
	QueryCosts(ctx context.Context, in *CostQueryRequest, opts ...grpc.CallOption) (*CostQueryResponse, error)
	// System operations
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
}

type mCPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPServiceClient(cc grpc.ClientConnInterface) MCPServiceClient {
	return &mCPServiceClient{cc}
}

func (c *mCPServiceClient) RegisterTool(ctx context.Context, in *ToolRegistrationRequest, opts ...grpc.CallOption) (*ToolRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolRegistrationResponse)
	err := c.cc.Invoke(ctx, MCPService_RegisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) DeregisterTool(ctx context.Context, in *ToolDeregistrationRequest, opts ...grpc.CallOption) (*ToolDeregistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolDeregistrationResponse)
	err := c.cc.Invoke(ctx, MCPService_DeregisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) DiscoverTools(ctx context.Context, in *ToolDiscoveryRequest, opts ...grpc.CallOption) (*ToolDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolDiscoveryResponse)
	err := c.cc.Invoke(ctx, MCPService_DiscoverTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) ExecuteTool(ctx context.Context, in *ToolExecutionRequest, opts ...grpc.CallOption) (*ToolExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolExecutionResponse)
	err := c.cc.Invoke(ctx, MCPService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) CheckToolHealth(ctx context.Context, in *ToolHealthRequest, opts ...grpc.CallOption) (*ToolHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolHealthResponse)
	err := c.cc.Invoke(ctx, MCPService_CheckToolHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) ReportCost(ctx context.Context, in *CostReportRequest, opts ...grpc.CallOption) (*CostReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CostReportResponse)
	err := c.cc.Invoke(ctx, MCPService_ReportCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) QueryCosts(ctx context.Context, in *CostQueryRequest, opts ...grpc.CallOption) (*CostQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CostQueryResponse)
	err := c.cc.Invoke(ctx, MCPService_QueryCosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MCPService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPServiceClient) GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfoResponse)
	err := c.cc.Invoke(ctx, MCPService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPServiceServer is the server API for MCPService service.
// All implementations must embed UnimplementedMCPServiceServer
// for forward compatibility.
//
// MCPService provides gRPC interface for Meta-Coordination Protocol
type MCPServiceServer interface {
	// Tool management
	RegisterTool(context.Context, *ToolRegistrationRequest) (*ToolRegistrationResponse, error)
	DeregisterTool(context.Context, *ToolDeregistrationRequest) (*ToolDeregistrationResponse, error)
	DiscoverTools(context.Context, *ToolDiscoveryRequest) (*ToolDiscoveryResponse, error)
	ExecuteTool(context.Context, *ToolExecutionRequest) (*ToolExecutionResponse, error)
	CheckToolHealth(context.Context, *ToolHealthRequest) (*ToolHealthResponse, error)
	// Cost tracking
	ReportCost(context.Context, *CostReportRequest) (*CostReportResponse, error)
	QueryCosts(context.Context, *CostQueryRequest) (*CostQueryResponse, error)
	// System operations
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error)
	mustEmbedUnimplementedMCPServiceServer()
}

// UnimplementedMCPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPServiceServer struct{}

func (UnimplementedMCPServiceServer) RegisterTool(context.Context, *ToolRegistrationRequest) (*ToolRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTool not implemented")
}
func (UnimplementedMCPServiceServer) DeregisterTool(context.Context, *ToolDeregistrationRequest) (*ToolDeregistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterTool not implemented")
}
func (UnimplementedMCPServiceServer) DiscoverTools(context.Context, *ToolDiscoveryRequest) (*ToolDiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverTools not implemented")
}
func (UnimplementedMCPServiceServer) ExecuteTool(context.Context, *ToolExecutionRequest) (*ToolExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedMCPServiceServer) CheckToolHealth(context.Context, *ToolHealthRequest) (*ToolHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToolHealth not implemented")
}
func (UnimplementedMCPServiceServer) ReportCost(context.Context, *CostReportRequest) (*CostReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportCost not implemented")
}
func (UnimplementedMCPServiceServer) QueryCosts(context.Context, *CostQueryRequest) (*CostQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCosts not implemented")
}
func (UnimplementedMCPServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMCPServiceServer) GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedMCPServiceServer) mustEmbedUnimplementedMCPServiceServer() {}
func (UnimplementedMCPServiceServer) testEmbeddedByValue()                    {}

// UnsafeMCPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPServiceServer will
// result in compilation errors.
type UnsafeMCPServiceServer interface {
	mustEmbedUnimplementedMCPServiceServer()
}

func RegisterMCPServiceServer(s grpc.ServiceRegistrar, srv MCPServiceServer) {
	// If the following call pancis, it indicates UnimplementedMCPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPService_ServiceDesc, srv)
}

func _MCPService_RegisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).RegisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_RegisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).RegisterTool(ctx, req.(*ToolRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_DeregisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolDeregistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).DeregisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_DeregisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).DeregisterTool(ctx, req.(*ToolDeregistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_DiscoverTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).DiscoverTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_DiscoverTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).DiscoverTools(ctx, req.(*ToolDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).ExecuteTool(ctx, req.(*ToolExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_CheckToolHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).CheckToolHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_CheckToolHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).CheckToolHealth(ctx, req.(*ToolHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_ReportCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CostReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).ReportCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_ReportCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).ReportCost(ctx, req.(*CostReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_QueryCosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CostQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).QueryCosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_QueryCosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).QueryCosts(ctx, req.(*CostQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPServiceServer).GetSystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MCPService_ServiceDesc is the grpc.ServiceDesc for MCPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.v1.MCPService",
	HandlerType: (*MCPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTool",
			Handler:    _MCPService_RegisterTool_Handler,
		},
		{
			MethodName: "DeregisterTool",
			Handler:    _MCPService_DeregisterTool_Handler,
		},
		{
			MethodName: "DiscoverTools",
			Handler:    _MCPService_DiscoverTools_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _MCPService_ExecuteTool_Handler,
		},
		{
			MethodName: "CheckToolHealth",
			Handler:    _MCPService_CheckToolHealth_Handler,
		},
		{
			MethodName: "ReportCost",
			Handler:    _MCPService_ReportCost_Handler,
		},
		{
			MethodName: "QueryCosts",
			Handler:    _MCPService_QueryCosts_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MCPService_Ping_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _MCPService_GetSystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mcp/v1/mcp.proto",
}
