// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/guild/v1/chat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage_MessageType int32

const (
	ChatMessage_USER_MESSAGE   ChatMessage_MessageType = 0
	ChatMessage_AGENT_RESPONSE ChatMessage_MessageType = 1
	ChatMessage_SYSTEM_MESSAGE ChatMessage_MessageType = 2
	ChatMessage_TOOL_REQUEST   ChatMessage_MessageType = 3
	ChatMessage_TOOL_RESULT    ChatMessage_MessageType = 4
	ChatMessage_AGENT_FRAGMENT ChatMessage_MessageType = 5 // Streaming response fragment
)

// Enum value maps for ChatMessage_MessageType.
var (
	ChatMessage_MessageType_name = map[int32]string{
		0: "USER_MESSAGE",
		1: "AGENT_RESPONSE",
		2: "SYSTEM_MESSAGE",
		3: "TOOL_REQUEST",
		4: "TOOL_RESULT",
		5: "AGENT_FRAGMENT",
	}
	ChatMessage_MessageType_value = map[string]int32{
		"USER_MESSAGE":   0,
		"AGENT_RESPONSE": 1,
		"SYSTEM_MESSAGE": 2,
		"TOOL_REQUEST":   3,
		"TOOL_RESULT":    4,
		"AGENT_FRAGMENT": 5,
	}
)

func (x ChatMessage_MessageType) Enum() *ChatMessage_MessageType {
	p := new(ChatMessage_MessageType)
	*p = x
	return p
}

func (x ChatMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[0].Descriptor()
}

func (ChatMessage_MessageType) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[0]
}

func (x ChatMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessage_MessageType.Descriptor instead.
func (ChatMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{2, 0}
}

type AgentThinking_ThinkingState int32

const (
	AgentThinking_ANALYZING   AgentThinking_ThinkingState = 0
	AgentThinking_PLANNING    AgentThinking_ThinkingState = 1
	AgentThinking_RESEARCHING AgentThinking_ThinkingState = 2
	AgentThinking_EXECUTING   AgentThinking_ThinkingState = 3
	AgentThinking_REVIEWING   AgentThinking_ThinkingState = 4
	AgentThinking_FINALIZING  AgentThinking_ThinkingState = 5
)

// Enum value maps for AgentThinking_ThinkingState.
var (
	AgentThinking_ThinkingState_name = map[int32]string{
		0: "ANALYZING",
		1: "PLANNING",
		2: "RESEARCHING",
		3: "EXECUTING",
		4: "REVIEWING",
		5: "FINALIZING",
	}
	AgentThinking_ThinkingState_value = map[string]int32{
		"ANALYZING":   0,
		"PLANNING":    1,
		"RESEARCHING": 2,
		"EXECUTING":   3,
		"REVIEWING":   4,
		"FINALIZING":  5,
	}
)

func (x AgentThinking_ThinkingState) Enum() *AgentThinking_ThinkingState {
	p := new(AgentThinking_ThinkingState)
	*p = x
	return p
}

func (x AgentThinking_ThinkingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentThinking_ThinkingState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[1].Descriptor()
}

func (AgentThinking_ThinkingState) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[1]
}

func (x AgentThinking_ThinkingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentThinking_ThinkingState.Descriptor instead.
func (AgentThinking_ThinkingState) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{3, 0}
}

type ToolExecution_ExecutionStatus int32

const (
	ToolExecution_PENDING           ToolExecution_ExecutionStatus = 0
	ToolExecution_AWAITING_APPROVAL ToolExecution_ExecutionStatus = 1
	ToolExecution_EXECUTING         ToolExecution_ExecutionStatus = 2
	ToolExecution_COMPLETED         ToolExecution_ExecutionStatus = 3
	ToolExecution_FAILED            ToolExecution_ExecutionStatus = 4
	ToolExecution_CANCELLED         ToolExecution_ExecutionStatus = 5
)

// Enum value maps for ToolExecution_ExecutionStatus.
var (
	ToolExecution_ExecutionStatus_name = map[int32]string{
		0: "PENDING",
		1: "AWAITING_APPROVAL",
		2: "EXECUTING",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	ToolExecution_ExecutionStatus_value = map[string]int32{
		"PENDING":           0,
		"AWAITING_APPROVAL": 1,
		"EXECUTING":         2,
		"COMPLETED":         3,
		"FAILED":            4,
		"CANCELLED":         5,
	}
)

func (x ToolExecution_ExecutionStatus) Enum() *ToolExecution_ExecutionStatus {
	p := new(ToolExecution_ExecutionStatus)
	*p = x
	return p
}

func (x ToolExecution_ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolExecution_ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[2].Descriptor()
}

func (ToolExecution_ExecutionStatus) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[2]
}

func (x ToolExecution_ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolExecution_ExecutionStatus.Descriptor instead.
func (ToolExecution_ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{4, 0}
}

type ChatControl_ControlAction int32

const (
	ChatControl_START_SESSION   ChatControl_ControlAction = 0
	ChatControl_END_SESSION     ChatControl_ControlAction = 1
	ChatControl_PAUSE_SESSION   ChatControl_ControlAction = 2
	ChatControl_RESUME_SESSION  ChatControl_ControlAction = 3
	ChatControl_INTERRUPT_AGENT ChatControl_ControlAction = 4
	ChatControl_REQUEST_STATUS  ChatControl_ControlAction = 5
)

// Enum value maps for ChatControl_ControlAction.
var (
	ChatControl_ControlAction_name = map[int32]string{
		0: "START_SESSION",
		1: "END_SESSION",
		2: "PAUSE_SESSION",
		3: "RESUME_SESSION",
		4: "INTERRUPT_AGENT",
		5: "REQUEST_STATUS",
	}
	ChatControl_ControlAction_value = map[string]int32{
		"START_SESSION":   0,
		"END_SESSION":     1,
		"PAUSE_SESSION":   2,
		"RESUME_SESSION":  3,
		"INTERRUPT_AGENT": 4,
		"REQUEST_STATUS":  5,
	}
)

func (x ChatControl_ControlAction) Enum() *ChatControl_ControlAction {
	p := new(ChatControl_ControlAction)
	*p = x
	return p
}

func (x ChatControl_ControlAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatControl_ControlAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[3].Descriptor()
}

func (ChatControl_ControlAction) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[3]
}

func (x ChatControl_ControlAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatControl_ControlAction.Descriptor instead.
func (ChatControl_ControlAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{5, 0}
}

type ChatEvent_EventType int32

const (
	ChatEvent_SESSION_STARTED    ChatEvent_EventType = 0
	ChatEvent_SESSION_ENDED      ChatEvent_EventType = 1
	ChatEvent_AGENT_JOINED       ChatEvent_EventType = 2
	ChatEvent_AGENT_LEFT         ChatEvent_EventType = 3
	ChatEvent_TOOL_DISCOVERED    ChatEvent_EventType = 4
	ChatEvent_MEMORY_ACCESSED    ChatEvent_EventType = 5
	ChatEvent_CONTEXT_UPDATED    ChatEvent_EventType = 6
	ChatEvent_ERROR_OCCURRED     ChatEvent_EventType = 7
	ChatEvent_COMMISSION_CREATED ChatEvent_EventType = 8
	ChatEvent_TASK_ASSIGNED      ChatEvent_EventType = 9
)

// Enum value maps for ChatEvent_EventType.
var (
	ChatEvent_EventType_name = map[int32]string{
		0: "SESSION_STARTED",
		1: "SESSION_ENDED",
		2: "AGENT_JOINED",
		3: "AGENT_LEFT",
		4: "TOOL_DISCOVERED",
		5: "MEMORY_ACCESSED",
		6: "CONTEXT_UPDATED",
		7: "ERROR_OCCURRED",
		8: "COMMISSION_CREATED",
		9: "TASK_ASSIGNED",
	}
	ChatEvent_EventType_value = map[string]int32{
		"SESSION_STARTED":    0,
		"SESSION_ENDED":      1,
		"AGENT_JOINED":       2,
		"AGENT_LEFT":         3,
		"TOOL_DISCOVERED":    4,
		"MEMORY_ACCESSED":    5,
		"CONTEXT_UPDATED":    6,
		"ERROR_OCCURRED":     7,
		"COMMISSION_CREATED": 8,
		"TASK_ASSIGNED":      9,
	}
)

func (x ChatEvent_EventType) Enum() *ChatEvent_EventType {
	p := new(ChatEvent_EventType)
	*p = x
	return p
}

func (x ChatEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[4].Descriptor()
}

func (ChatEvent_EventType) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[4]
}

func (x ChatEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatEvent_EventType.Descriptor instead.
func (ChatEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{7, 0}
}

type ChatError_ErrorCode int32

const (
	ChatError_UNKNOWN               ChatError_ErrorCode = 0
	ChatError_INVALID_SESSION       ChatError_ErrorCode = 1
	ChatError_AGENT_UNAVAILABLE     ChatError_ErrorCode = 2
	ChatError_TOOL_EXECUTION_FAILED ChatError_ErrorCode = 3
	ChatError_PERMISSION_DENIED     ChatError_ErrorCode = 4
	ChatError_RATE_LIMITED          ChatError_ErrorCode = 5
	ChatError_CONTEXT_TOO_LARGE     ChatError_ErrorCode = 6
	ChatError_INVALID_REQUEST       ChatError_ErrorCode = 7
)

// Enum value maps for ChatError_ErrorCode.
var (
	ChatError_ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_SESSION",
		2: "AGENT_UNAVAILABLE",
		3: "TOOL_EXECUTION_FAILED",
		4: "PERMISSION_DENIED",
		5: "RATE_LIMITED",
		6: "CONTEXT_TOO_LARGE",
		7: "INVALID_REQUEST",
	}
	ChatError_ErrorCode_value = map[string]int32{
		"UNKNOWN":               0,
		"INVALID_SESSION":       1,
		"AGENT_UNAVAILABLE":     2,
		"TOOL_EXECUTION_FAILED": 3,
		"PERMISSION_DENIED":     4,
		"RATE_LIMITED":          5,
		"CONTEXT_TOO_LARGE":     6,
		"INVALID_REQUEST":       7,
	}
)

func (x ChatError_ErrorCode) Enum() *ChatError_ErrorCode {
	p := new(ChatError_ErrorCode)
	*p = x
	return p
}

func (x ChatError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[5].Descriptor()
}

func (ChatError_ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[5]
}

func (x ChatError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatError_ErrorCode.Descriptor instead.
func (ChatError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{8, 0}
}

type ChatSession_SessionStatus int32

const (
	ChatSession_ACTIVE ChatSession_SessionStatus = 0
	ChatSession_PAUSED ChatSession_SessionStatus = 1
	ChatSession_ENDED  ChatSession_SessionStatus = 2
	ChatSession_ERROR  ChatSession_SessionStatus = 3
)

// Enum value maps for ChatSession_SessionStatus.
var (
	ChatSession_SessionStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "PAUSED",
		2: "ENDED",
		3: "ERROR",
	}
	ChatSession_SessionStatus_value = map[string]int32{
		"ACTIVE": 0,
		"PAUSED": 1,
		"ENDED":  2,
		"ERROR":  3,
	}
)

func (x ChatSession_SessionStatus) Enum() *ChatSession_SessionStatus {
	p := new(ChatSession_SessionStatus)
	*p = x
	return p
}

func (x ChatSession_SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatSession_SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_v1_chat_proto_enumTypes[6].Descriptor()
}

func (ChatSession_SessionStatus) Type() protoreflect.EnumType {
	return &file_proto_guild_v1_chat_proto_enumTypes[6]
}

func (x ChatSession_SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatSession_SessionStatus.Descriptor instead.
func (ChatSession_SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{9, 0}
}

// Chat request message
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ChatRequest_Message
	//	*ChatRequest_Control
	//	*ChatRequest_ToolApproval
	Request       isChatRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetRequest() isChatRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ChatRequest) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Request.(*ChatRequest_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatRequest) GetControl() *ChatControl {
	if x != nil {
		if x, ok := x.Request.(*ChatRequest_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *ChatRequest) GetToolApproval() *ToolApproval {
	if x != nil {
		if x, ok := x.Request.(*ChatRequest_ToolApproval); ok {
			return x.ToolApproval
		}
	}
	return nil
}

type isChatRequest_Request interface {
	isChatRequest_Request()
}

type ChatRequest_Message struct {
	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatRequest_Control struct {
	Control *ChatControl `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

type ChatRequest_ToolApproval struct {
	ToolApproval *ToolApproval `protobuf:"bytes,3,opt,name=tool_approval,json=toolApproval,proto3,oneof"`
}

func (*ChatRequest_Message) isChatRequest_Request() {}

func (*ChatRequest_Control) isChatRequest_Request() {}

func (*ChatRequest_ToolApproval) isChatRequest_Request() {}

// Chat response message
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ChatResponse_Message
	//	*ChatResponse_Thinking
	//	*ChatResponse_ToolExecution
	//	*ChatResponse_Event
	//	*ChatResponse_Error
	Response      isChatResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetResponse() isChatResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ChatResponse) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Response.(*ChatResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatResponse) GetThinking() *AgentThinking {
	if x != nil {
		if x, ok := x.Response.(*ChatResponse_Thinking); ok {
			return x.Thinking
		}
	}
	return nil
}

func (x *ChatResponse) GetToolExecution() *ToolExecution {
	if x != nil {
		if x, ok := x.Response.(*ChatResponse_ToolExecution); ok {
			return x.ToolExecution
		}
	}
	return nil
}

func (x *ChatResponse) GetEvent() *ChatEvent {
	if x != nil {
		if x, ok := x.Response.(*ChatResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ChatResponse) GetError() *ChatError {
	if x != nil {
		if x, ok := x.Response.(*ChatResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChatResponse_Response interface {
	isChatResponse_Response()
}

type ChatResponse_Message struct {
	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatResponse_Thinking struct {
	Thinking *AgentThinking `protobuf:"bytes,2,opt,name=thinking,proto3,oneof"`
}

type ChatResponse_ToolExecution struct {
	ToolExecution *ToolExecution `protobuf:"bytes,3,opt,name=tool_execution,json=toolExecution,proto3,oneof"`
}

type ChatResponse_Event struct {
	Event *ChatEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type ChatResponse_Error struct {
	Error *ChatError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ChatResponse_Message) isChatResponse_Response() {}

func (*ChatResponse_Thinking) isChatResponse_Response() {}

func (*ChatResponse_ToolExecution) isChatResponse_Response() {}

func (*ChatResponse_Event) isChatResponse_Response() {}

func (*ChatResponse_Error) isChatResponse_Response() {}

// Core chat message
type ChatMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionId     string                  `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SenderId      string                  `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // agent_id or "user"
	SenderName    string                  `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content       string                  `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          ChatMessage_MessageType `protobuf:"varint,5,opt,name=type,proto3,enum=guild.v1.ChatMessage_MessageType" json:"type,omitempty"`
	Timestamp     int64                   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string       `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetType() ChatMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return ChatMessage_USER_MESSAGE
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Agent thinking indicator
type AgentThinking struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	AgentId       string                      `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                      `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	SessionId     string                      `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         AgentThinking_ThinkingState `protobuf:"varint,4,opt,name=state,proto3,enum=guild.v1.AgentThinking_ThinkingState" json:"state,omitempty"`
	Description   string                      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp     int64                       `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentThinking) Reset() {
	*x = AgentThinking{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentThinking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentThinking) ProtoMessage() {}

func (x *AgentThinking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentThinking.ProtoReflect.Descriptor instead.
func (*AgentThinking) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *AgentThinking) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentThinking) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentThinking) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentThinking) GetState() AgentThinking_ThinkingState {
	if x != nil {
		return x.State
	}
	return AgentThinking_ANALYZING
}

func (x *AgentThinking) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentThinking) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Tool execution status
type ToolExecution struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	ToolId              string                        `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolName            string                        `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	AgentId             string                        `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId           string                        `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Parameters          map[string]string             `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status              ToolExecution_ExecutionStatus `protobuf:"varint,6,opt,name=status,proto3,enum=guild.v1.ToolExecution_ExecutionStatus" json:"status,omitempty"`
	Progress            float64                       `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	Result              string                        `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	Error               string                        `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt           int64                         `protobuf:"varint,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt           int64                         `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EstimatedCost       float64                       `protobuf:"fixed64,12,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	RequiredPermissions []string                      `protobuf:"bytes,13,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	RequiresApproval    bool                          `protobuf:"varint,14,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ToolExecution) Reset() {
	*x = ToolExecution{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecution) ProtoMessage() {}

func (x *ToolExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecution.ProtoReflect.Descriptor instead.
func (*ToolExecution) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ToolExecution) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolExecution) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolExecution) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToolExecution) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolExecution) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ToolExecution) GetStatus() ToolExecution_ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ToolExecution_PENDING
}

func (x *ToolExecution) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ToolExecution) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolExecution) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ToolExecution) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ToolExecution) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *ToolExecution) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *ToolExecution) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

// Chat session control
type ChatControl struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Action        ChatControl_ControlAction `protobuf:"varint,1,opt,name=action,proto3,enum=guild.v1.ChatControl_ControlAction" json:"action,omitempty"`
	SessionId     string                    `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Parameters    map[string]string         `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatControl) Reset() {
	*x = ChatControl{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatControl) ProtoMessage() {}

func (x *ChatControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatControl.ProtoReflect.Descriptor instead.
func (*ChatControl) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatControl) GetAction() ChatControl_ControlAction {
	if x != nil {
		return x.Action
	}
	return ChatControl_START_SESSION
}

func (x *ChatControl) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatControl) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Tool approval from user
type ToolApproval struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ToolExecutionId    string                 `protobuf:"bytes,1,opt,name=tool_execution_id,json=toolExecutionId,proto3" json:"tool_execution_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Approved           bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ModifiedParameters map[string]string      `protobuf:"bytes,5,rep,name=modified_parameters,json=modifiedParameters,proto3" json:"modified_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ToolApproval) Reset() {
	*x = ToolApproval{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolApproval) ProtoMessage() {}

func (x *ToolApproval) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolApproval.ProtoReflect.Descriptor instead.
func (*ToolApproval) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ToolApproval) GetToolExecutionId() string {
	if x != nil {
		return x.ToolExecutionId
	}
	return ""
}

func (x *ToolApproval) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolApproval) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ToolApproval) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ToolApproval) GetModifiedParameters() map[string]string {
	if x != nil {
		return x.ModifiedParameters
	}
	return nil
}

// Chat events
type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          ChatEvent_EventType    `protobuf:"varint,2,opt,name=type,proto3,enum=guild.v1.ChatEvent_EventType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatEvent) GetType() ChatEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ChatEvent_SESSION_STARTED
}

func (x *ChatEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Chat error
type ChatError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          ChatError_ErrorCode    `protobuf:"varint,2,opt,name=code,proto3,enum=guild.v1.ChatError_ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatError) Reset() {
	*x = ChatError{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatError) ProtoMessage() {}

func (x *ChatError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatError.ProtoReflect.Descriptor instead.
func (*ChatError) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ChatError) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatError) GetCode() ChatError_ErrorCode {
	if x != nil {
		return x.Code
	}
	return ChatError_UNKNOWN
}

func (x *ChatError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ChatError) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Chat session management
type ChatSession struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AgentIds      []string                  `protobuf:"bytes,3,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	CampaignId    string                    `protobuf:"bytes,4,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Status        ChatSession_SessionStatus `protobuf:"varint,5,opt,name=status,proto3,enum=guild.v1.ChatSession_SessionStatus" json:"status,omitempty"`
	CreatedAt     int64                     `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActivity  int64                     `protobuf:"varint,7,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	Metadata      map[string]string         `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Context       *SessionContext           `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatSession) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *ChatSession) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ChatSession) GetStatus() ChatSession_SessionStatus {
	if x != nil {
		return x.Status
	}
	return ChatSession_ACTIVE
}

func (x *ChatSession) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChatSession) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *ChatSession) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChatSession) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// Session context information
type SessionContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath       string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	CurrentCommission string                 `protobuf:"bytes,2,opt,name=current_commission,json=currentCommission,proto3" json:"current_commission,omitempty"`
	ActiveTasks       []string               `protobuf:"bytes,3,rep,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	Environment       map[string]string      `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AvailableTools    []string               `protobuf:"bytes,5,rep,name=available_tools,json=availableTools,proto3" json:"available_tools,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *SessionContext) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SessionContext) GetCurrentCommission() string {
	if x != nil {
		return x.CurrentCommission
	}
	return ""
}

func (x *SessionContext) GetActiveTasks() []string {
	if x != nil {
		return x.ActiveTasks
	}
	return nil
}

func (x *SessionContext) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *SessionContext) GetAvailableTools() []string {
	if x != nil {
		return x.AvailableTools
	}
	return nil
}

// Request/Response messages for session management
type CreateChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AgentIds      []string               `protobuf:"bytes,2,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	CampaignId    string                 `protobuf:"bytes,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Context       *SessionContext        `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionRequest) Reset() {
	*x = CreateChatSessionRequest{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionRequest) ProtoMessage() {}

func (x *CreateChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *CreateChatSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatSessionRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *CreateChatSessionRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CreateChatSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateChatSessionRequest) GetContext() *SessionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type EndChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndChatSessionRequest) Reset() {
	*x = EndChatSessionRequest{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndChatSessionRequest) ProtoMessage() {}

func (x *EndChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndChatSessionRequest.ProtoReflect.Descriptor instead.
func (*EndChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *EndChatSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndChatSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndChatSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Summary       *ChatSessionSummary    `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndChatSessionResponse) Reset() {
	*x = EndChatSessionResponse{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndChatSessionResponse) ProtoMessage() {}

func (x *EndChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndChatSessionResponse.ProtoReflect.Descriptor instead.
func (*EndChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *EndChatSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EndChatSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndChatSessionResponse) GetSummary() *ChatSessionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type ListChatSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeEnded  bool                   `protobuf:"varint,1,opt,name=include_ended,json=includeEnded,proto3" json:"include_ended,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsRequest) Reset() {
	*x = ListChatSessionsRequest{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsRequest) ProtoMessage() {}

func (x *ListChatSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListChatSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ListChatSessionsRequest) GetIncludeEnded() bool {
	if x != nil {
		return x.IncludeEnded
	}
	return false
}

func (x *ListChatSessionsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ListChatSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListChatSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ChatSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsResponse) Reset() {
	*x = ListChatSessionsResponse{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsResponse) ProtoMessage() {}

func (x *ListChatSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListChatSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ListChatSessionsResponse) GetSessions() []*ChatSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListChatSessionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetChatHistoryRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SinceTimestamp        int64                  `protobuf:"varint,2,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"`
	Limit                 int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeSystemMessages bool                   `protobuf:"varint,4,opt,name=include_system_messages,json=includeSystemMessages,proto3" json:"include_system_messages,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *GetChatHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryRequest) GetIncludeSystemMessages() bool {
	if x != nil {
		return x.IncludeSystemMessages
	}
	return false
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Events        []*ChatEvent           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryResponse) GetEvents() []*ChatEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetChatHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetChatHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Chat session summary
type ChatSessionSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalMessages  int32                  `protobuf:"varint,1,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	ToolsExecuted  int32                  `protobuf:"varint,2,opt,name=tools_executed,json=toolsExecuted,proto3" json:"tools_executed,omitempty"`
	TotalCost      float64                `protobuf:"fixed64,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	TasksCreated   int32                  `protobuf:"varint,4,opt,name=tasks_created,json=tasksCreated,proto3" json:"tasks_created,omitempty"`
	AgentsInvolved []string               `protobuf:"bytes,5,rep,name=agents_involved,json=agentsInvolved,proto3" json:"agents_involved,omitempty"`
	Outcome        string                 `protobuf:"bytes,6,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatSessionSummary) Reset() {
	*x = ChatSessionSummary{}
	mi := &file_proto_guild_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSessionSummary) ProtoMessage() {}

func (x *ChatSessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSessionSummary.ProtoReflect.Descriptor instead.
func (*ChatSessionSummary) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *ChatSessionSummary) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *ChatSessionSummary) GetToolsExecuted() int32 {
	if x != nil {
		return x.ToolsExecuted
	}
	return 0
}

func (x *ChatSessionSummary) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ChatSessionSummary) GetTasksCreated() int32 {
	if x != nil {
		return x.TasksCreated
	}
	return 0
}

func (x *ChatSessionSummary) GetAgentsInvolved() []string {
	if x != nil {
		return x.AgentsInvolved
	}
	return nil
}

func (x *ChatSessionSummary) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_proto_guild_v1_chat_proto protoreflect.FileDescriptor

const file_proto_guild_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x19proto/guild/v1/chat.proto\x12\bguild.v1\"\xbd\x01\n" +
	"\vChatRequest\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x15.guild.v1.ChatMessageH\x00R\amessage\x121\n" +
	"\acontrol\x18\x02 \x01(\v2\x15.guild.v1.ChatControlH\x00R\acontrol\x12=\n" +
	"\rtool_approval\x18\x03 \x01(\v2\x16.guild.v1.ToolApprovalH\x00R\ftoolApprovalB\t\n" +
	"\arequest\"\xa0\x02\n" +
	"\fChatResponse\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x15.guild.v1.ChatMessageH\x00R\amessage\x125\n" +
	"\bthinking\x18\x02 \x01(\v2\x17.guild.v1.AgentThinkingH\x00R\bthinking\x12@\n" +
	"\x0etool_execution\x18\x03 \x01(\v2\x17.guild.v1.ToolExecutionH\x00R\rtoolExecution\x12+\n" +
	"\x05event\x18\x04 \x01(\v2\x13.guild.v1.ChatEventH\x00R\x05event\x12+\n" +
	"\x05error\x18\x05 \x01(\v2\x13.guild.v1.ChatErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xd7\x03\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x125\n" +
	"\x04type\x18\x05 \x01(\x0e2!.guild.v1.ChatMessage.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.guild.v1.ChatMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\vMessageType\x12\x10\n" +
	"\fUSER_MESSAGE\x10\x00\x12\x12\n" +
	"\x0eAGENT_RESPONSE\x10\x01\x12\x12\n" +
	"\x0eSYSTEM_MESSAGE\x10\x02\x12\x10\n" +
	"\fTOOL_REQUEST\x10\x03\x12\x0f\n" +
	"\vTOOL_RESULT\x10\x04\x12\x12\n" +
	"\x0eAGENT_FRAGMENT\x10\x05\"\xd2\x02\n" +
	"\rAgentThinking\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12;\n" +
	"\x05state\x18\x04 \x01(\x0e2%.guild.v1.AgentThinking.ThinkingStateR\x05state\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"k\n" +
	"\rThinkingState\x12\r\n" +
	"\tANALYZING\x10\x00\x12\f\n" +
	"\bPLANNING\x10\x01\x12\x0f\n" +
	"\vRESEARCHING\x10\x02\x12\r\n" +
	"\tEXECUTING\x10\x03\x12\r\n" +
	"\tREVIEWING\x10\x04\x12\x0e\n" +
	"\n" +
	"FINALIZING\x10\x05\"\xc7\x05\n" +
	"\rToolExecution\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12G\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2'.guild.v1.ToolExecution.ParametersEntryR\n" +
	"parameters\x12?\n" +
	"\x06status\x18\x06 \x01(\x0e2'.guild.v1.ToolExecution.ExecutionStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\x12\x16\n" +
	"\x06result\x18\b \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12%\n" +
	"\x0eestimated_cost\x18\f \x01(\x01R\restimatedCost\x121\n" +
	"\x14required_permissions\x18\r \x03(\tR\x13requiredPermissions\x12+\n" +
	"\x11requires_approval\x18\x0e \x01(\bR\x10requiresApproval\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x0fExecutionStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x15\n" +
	"\x11AWAITING_APPROVAL\x10\x01\x12\r\n" +
	"\tEXECUTING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\"\xf5\x02\n" +
	"\vChatControl\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.guild.v1.ChatControl.ControlActionR\x06action\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12E\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2%.guild.v1.ChatControl.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\rControlAction\x12\x11\n" +
	"\rSTART_SESSION\x10\x00\x12\x0f\n" +
	"\vEND_SESSION\x10\x01\x12\x11\n" +
	"\rPAUSE_SESSION\x10\x02\x12\x12\n" +
	"\x0eRESUME_SESSION\x10\x03\x12\x13\n" +
	"\x0fINTERRUPT_AGENT\x10\x04\x12\x12\n" +
	"\x0eREQUEST_STATUS\x10\x05\"\xb5\x02\n" +
	"\fToolApproval\x12*\n" +
	"\x11tool_execution_id\x18\x01 \x01(\tR\x0ftoolExecutionId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12_\n" +
	"\x13modified_parameters\x18\x05 \x03(\v2..guild.v1.ToolApproval.ModifiedParametersEntryR\x12modifiedParameters\x1aE\n" +
	"\x17ModifiedParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x03\n" +
	"\tChatEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.guild.v1.ChatEvent.EventTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x04data\x18\x04 \x03(\v2\x1d.guild.v1.ChatEvent.DataEntryR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\tEventType\x12\x13\n" +
	"\x0fSESSION_STARTED\x10\x00\x12\x11\n" +
	"\rSESSION_ENDED\x10\x01\x12\x10\n" +
	"\fAGENT_JOINED\x10\x02\x12\x0e\n" +
	"\n" +
	"AGENT_LEFT\x10\x03\x12\x13\n" +
	"\x0fTOOL_DISCOVERED\x10\x04\x12\x13\n" +
	"\x0fMEMORY_ACCESSED\x10\x05\x12\x13\n" +
	"\x0fCONTEXT_UPDATED\x10\x06\x12\x12\n" +
	"\x0eERROR_OCCURRED\x10\a\x12\x16\n" +
	"\x12COMMISSION_CREATED\x10\b\x12\x11\n" +
	"\rTASK_ASSIGNED\x10\t\"\xc4\x03\n" +
	"\tChatError\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\x04code\x18\x02 \x01(\x0e2\x1d.guild.v1.ChatError.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12:\n" +
	"\adetails\x18\x04 \x03(\v2 .guild.v1.ChatError.DetailsEntryR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fINVALID_SESSION\x10\x01\x12\x15\n" +
	"\x11AGENT_UNAVAILABLE\x10\x02\x12\x19\n" +
	"\x15TOOL_EXECUTION_FAILED\x10\x03\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x04\x12\x10\n" +
	"\fRATE_LIMITED\x10\x05\x12\x15\n" +
	"\x11CONTEXT_TOO_LARGE\x10\x06\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\a\"\xe1\x03\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tagent_ids\x18\x03 \x03(\tR\bagentIds\x12\x1f\n" +
	"\vcampaign_id\x18\x04 \x01(\tR\n" +
	"campaignId\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.guild.v1.ChatSession.SessionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12#\n" +
	"\rlast_activity\x18\a \x01(\x03R\flastActivity\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.guild.v1.ChatSession.MetadataEntryR\bmetadata\x122\n" +
	"\acontext\x18\t \x01(\v2\x18.guild.v1.SessionContextR\acontext\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\rSessionStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x01\x12\t\n" +
	"\x05ENDED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"\xbb\x02\n" +
	"\x0eSessionContext\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12-\n" +
	"\x12current_commission\x18\x02 \x01(\tR\x11currentCommission\x12!\n" +
	"\factive_tasks\x18\x03 \x03(\tR\vactiveTasks\x12K\n" +
	"\venvironment\x18\x04 \x03(\v2).guild.v1.SessionContext.EnvironmentEntryR\venvironment\x12'\n" +
	"\x0favailable_tools\x18\x05 \x03(\tR\x0eavailableTools\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\x18CreateChatSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tagent_ids\x18\x02 \x03(\tR\bagentIds\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\tR\n" +
	"campaignId\x12L\n" +
	"\bmetadata\x18\x04 \x03(\v20.guild.v1.CreateChatSessionRequest.MetadataEntryR\bmetadata\x122\n" +
	"\acontext\x18\x05 \x01(\v2\x18.guild.v1.SessionContextR\acontext\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x15EndChatSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x84\x01\n" +
	"\x16EndChatSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\asummary\x18\x03 \x01(\v2\x1c.guild.v1.ChatSessionSummaryR\asummary\"u\n" +
	"\x17ListChatSessionsRequest\x12#\n" +
	"\rinclude_ended\x18\x01 \x01(\bR\fincludeEnded\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"n\n" +
	"\x18ListChatSessionsResponse\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.guild.v1.ChatSessionR\bsessions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xad\x01\n" +
	"\x15GetChatHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\x03R\x0esinceTimestamp\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x126\n" +
	"\x17include_system_messages\x18\x04 \x01(\bR\x15includeSystemMessages\"\xb4\x01\n" +
	"\x16GetChatHistoryResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.guild.v1.ChatMessageR\bmessages\x12+\n" +
	"\x06events\x18\x02 \x03(\v2\x13.guild.v1.ChatEventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xe9\x01\n" +
	"\x12ChatSessionSummary\x12%\n" +
	"\x0etotal_messages\x18\x01 \x01(\x05R\rtotalMessages\x12%\n" +
	"\x0etools_executed\x18\x02 \x01(\x05R\rtoolsExecuted\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\x01R\ttotalCost\x12#\n" +
	"\rtasks_created\x18\x04 \x01(\x05R\ftasksCreated\x12'\n" +
	"\x0fagents_involved\x18\x05 \x03(\tR\x0eagentsInvolved\x12\x18\n" +
	"\aoutcome\x18\x06 \x01(\tR\aoutcome2\x9d\x03\n" +
	"\vChatService\x129\n" +
	"\x04Chat\x12\x15.guild.v1.ChatRequest\x1a\x16.guild.v1.ChatResponse(\x010\x01\x12S\n" +
	"\x0eGetChatHistory\x12\x1f.guild.v1.GetChatHistoryRequest\x1a .guild.v1.GetChatHistoryResponse\x12N\n" +
	"\x11CreateChatSession\x12\".guild.v1.CreateChatSessionRequest\x1a\x15.guild.v1.ChatSession\x12S\n" +
	"\x0eEndChatSession\x12\x1f.guild.v1.EndChatSessionRequest\x1a .guild.v1.EndChatSessionResponse\x12Y\n" +
	"\x10ListChatSessions\x12!.guild.v1.ListChatSessionsRequest\x1a\".guild.v1.ListChatSessionsResponseB4Z2github.com/lancekrogers/guild/pkg/grpc/pb/guild/v1b\x06proto3"

var (
	file_proto_guild_v1_chat_proto_rawDescOnce sync.Once
	file_proto_guild_v1_chat_proto_rawDescData []byte
)

func file_proto_guild_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_guild_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_guild_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_guild_v1_chat_proto_rawDesc), len(file_proto_guild_v1_chat_proto_rawDesc)))
	})
	return file_proto_guild_v1_chat_proto_rawDescData
}

var file_proto_guild_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_guild_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_guild_v1_chat_proto_goTypes = []any{
	(ChatMessage_MessageType)(0),       // 0: guild.v1.ChatMessage.MessageType
	(AgentThinking_ThinkingState)(0),   // 1: guild.v1.AgentThinking.ThinkingState
	(ToolExecution_ExecutionStatus)(0), // 2: guild.v1.ToolExecution.ExecutionStatus
	(ChatControl_ControlAction)(0),     // 3: guild.v1.ChatControl.ControlAction
	(ChatEvent_EventType)(0),           // 4: guild.v1.ChatEvent.EventType
	(ChatError_ErrorCode)(0),           // 5: guild.v1.ChatError.ErrorCode
	(ChatSession_SessionStatus)(0),     // 6: guild.v1.ChatSession.SessionStatus
	(*ChatRequest)(nil),                // 7: guild.v1.ChatRequest
	(*ChatResponse)(nil),               // 8: guild.v1.ChatResponse
	(*ChatMessage)(nil),                // 9: guild.v1.ChatMessage
	(*AgentThinking)(nil),              // 10: guild.v1.AgentThinking
	(*ToolExecution)(nil),              // 11: guild.v1.ToolExecution
	(*ChatControl)(nil),                // 12: guild.v1.ChatControl
	(*ToolApproval)(nil),               // 13: guild.v1.ToolApproval
	(*ChatEvent)(nil),                  // 14: guild.v1.ChatEvent
	(*ChatError)(nil),                  // 15: guild.v1.ChatError
	(*ChatSession)(nil),                // 16: guild.v1.ChatSession
	(*SessionContext)(nil),             // 17: guild.v1.SessionContext
	(*CreateChatSessionRequest)(nil),   // 18: guild.v1.CreateChatSessionRequest
	(*EndChatSessionRequest)(nil),      // 19: guild.v1.EndChatSessionRequest
	(*EndChatSessionResponse)(nil),     // 20: guild.v1.EndChatSessionResponse
	(*ListChatSessionsRequest)(nil),    // 21: guild.v1.ListChatSessionsRequest
	(*ListChatSessionsResponse)(nil),   // 22: guild.v1.ListChatSessionsResponse
	(*GetChatHistoryRequest)(nil),      // 23: guild.v1.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),     // 24: guild.v1.GetChatHistoryResponse
	(*ChatSessionSummary)(nil),         // 25: guild.v1.ChatSessionSummary
	nil,                                // 26: guild.v1.ChatMessage.MetadataEntry
	nil,                                // 27: guild.v1.ToolExecution.ParametersEntry
	nil,                                // 28: guild.v1.ChatControl.ParametersEntry
	nil,                                // 29: guild.v1.ToolApproval.ModifiedParametersEntry
	nil,                                // 30: guild.v1.ChatEvent.DataEntry
	nil,                                // 31: guild.v1.ChatError.DetailsEntry
	nil,                                // 32: guild.v1.ChatSession.MetadataEntry
	nil,                                // 33: guild.v1.SessionContext.EnvironmentEntry
	nil,                                // 34: guild.v1.CreateChatSessionRequest.MetadataEntry
}
var file_proto_guild_v1_chat_proto_depIdxs = []int32{
	9,  // 0: guild.v1.ChatRequest.message:type_name -> guild.v1.ChatMessage
	12, // 1: guild.v1.ChatRequest.control:type_name -> guild.v1.ChatControl
	13, // 2: guild.v1.ChatRequest.tool_approval:type_name -> guild.v1.ToolApproval
	9,  // 3: guild.v1.ChatResponse.message:type_name -> guild.v1.ChatMessage
	10, // 4: guild.v1.ChatResponse.thinking:type_name -> guild.v1.AgentThinking
	11, // 5: guild.v1.ChatResponse.tool_execution:type_name -> guild.v1.ToolExecution
	14, // 6: guild.v1.ChatResponse.event:type_name -> guild.v1.ChatEvent
	15, // 7: guild.v1.ChatResponse.error:type_name -> guild.v1.ChatError
	0,  // 8: guild.v1.ChatMessage.type:type_name -> guild.v1.ChatMessage.MessageType
	26, // 9: guild.v1.ChatMessage.metadata:type_name -> guild.v1.ChatMessage.MetadataEntry
	1,  // 10: guild.v1.AgentThinking.state:type_name -> guild.v1.AgentThinking.ThinkingState
	27, // 11: guild.v1.ToolExecution.parameters:type_name -> guild.v1.ToolExecution.ParametersEntry
	2,  // 12: guild.v1.ToolExecution.status:type_name -> guild.v1.ToolExecution.ExecutionStatus
	3,  // 13: guild.v1.ChatControl.action:type_name -> guild.v1.ChatControl.ControlAction
	28, // 14: guild.v1.ChatControl.parameters:type_name -> guild.v1.ChatControl.ParametersEntry
	29, // 15: guild.v1.ToolApproval.modified_parameters:type_name -> guild.v1.ToolApproval.ModifiedParametersEntry
	4,  // 16: guild.v1.ChatEvent.type:type_name -> guild.v1.ChatEvent.EventType
	30, // 17: guild.v1.ChatEvent.data:type_name -> guild.v1.ChatEvent.DataEntry
	5,  // 18: guild.v1.ChatError.code:type_name -> guild.v1.ChatError.ErrorCode
	31, // 19: guild.v1.ChatError.details:type_name -> guild.v1.ChatError.DetailsEntry
	6,  // 20: guild.v1.ChatSession.status:type_name -> guild.v1.ChatSession.SessionStatus
	32, // 21: guild.v1.ChatSession.metadata:type_name -> guild.v1.ChatSession.MetadataEntry
	17, // 22: guild.v1.ChatSession.context:type_name -> guild.v1.SessionContext
	33, // 23: guild.v1.SessionContext.environment:type_name -> guild.v1.SessionContext.EnvironmentEntry
	34, // 24: guild.v1.CreateChatSessionRequest.metadata:type_name -> guild.v1.CreateChatSessionRequest.MetadataEntry
	17, // 25: guild.v1.CreateChatSessionRequest.context:type_name -> guild.v1.SessionContext
	25, // 26: guild.v1.EndChatSessionResponse.summary:type_name -> guild.v1.ChatSessionSummary
	16, // 27: guild.v1.ListChatSessionsResponse.sessions:type_name -> guild.v1.ChatSession
	9,  // 28: guild.v1.GetChatHistoryResponse.messages:type_name -> guild.v1.ChatMessage
	14, // 29: guild.v1.GetChatHistoryResponse.events:type_name -> guild.v1.ChatEvent
	7,  // 30: guild.v1.ChatService.Chat:input_type -> guild.v1.ChatRequest
	23, // 31: guild.v1.ChatService.GetChatHistory:input_type -> guild.v1.GetChatHistoryRequest
	18, // 32: guild.v1.ChatService.CreateChatSession:input_type -> guild.v1.CreateChatSessionRequest
	19, // 33: guild.v1.ChatService.EndChatSession:input_type -> guild.v1.EndChatSessionRequest
	21, // 34: guild.v1.ChatService.ListChatSessions:input_type -> guild.v1.ListChatSessionsRequest
	8,  // 35: guild.v1.ChatService.Chat:output_type -> guild.v1.ChatResponse
	24, // 36: guild.v1.ChatService.GetChatHistory:output_type -> guild.v1.GetChatHistoryResponse
	16, // 37: guild.v1.ChatService.CreateChatSession:output_type -> guild.v1.ChatSession
	20, // 38: guild.v1.ChatService.EndChatSession:output_type -> guild.v1.EndChatSessionResponse
	22, // 39: guild.v1.ChatService.ListChatSessions:output_type -> guild.v1.ListChatSessionsResponse
	35, // [35:40] is the sub-list for method output_type
	30, // [30:35] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_guild_v1_chat_proto_init() }
func file_proto_guild_v1_chat_proto_init() {
	if File_proto_guild_v1_chat_proto != nil {
		return
	}
	file_proto_guild_v1_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatRequest_Message)(nil),
		(*ChatRequest_Control)(nil),
		(*ChatRequest_ToolApproval)(nil),
	}
	file_proto_guild_v1_chat_proto_msgTypes[1].OneofWrappers = []any{
		(*ChatResponse_Message)(nil),
		(*ChatResponse_Thinking)(nil),
		(*ChatResponse_ToolExecution)(nil),
		(*ChatResponse_Event)(nil),
		(*ChatResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_guild_v1_chat_proto_rawDesc), len(file_proto_guild_v1_chat_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_guild_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_guild_v1_chat_proto_depIdxs,
		EnumInfos:         file_proto_guild_v1_chat_proto_enumTypes,
		MessageInfos:      file_proto_guild_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_guild_v1_chat_proto = out.File
	file_proto_guild_v1_chat_proto_goTypes = nil
	file_proto_guild_v1_chat_proto_depIdxs = nil
}
