// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/guild/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a system event
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_guild_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// StreamEventsRequest configures event streaming
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type patterns to subscribe to (e.g., "task.*", "agent.*")
	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// If true, subscribe to all events
	SubscribeAll bool `protobuf:"varint,2,opt,name=subscribe_all,json=subscribeAll,proto3" json:"subscribe_all,omitempty"`
	// Optional: only events after this timestamp
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3,oneof" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_guild_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *StreamEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *StreamEventsRequest) GetSubscribeAll() bool {
	if x != nil {
		return x.SubscribeAll
	}
	return false
}

func (x *StreamEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// PublishEventRequest publishes an event
type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_proto_guild_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *PublishEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// PublishEventResponse confirms event publication
type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_proto_guild_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *PublishEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_guild_v1_events_proto protoreflect.FileDescriptor

const file_proto_guild_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/guild/v1/events.proto\x12\bguild.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaa\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x9c\x01\n" +
	"\x13StreamEventsRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\x12#\n" +
	"\rsubscribe_all\x18\x02 \x01(\bR\fsubscribeAll\x125\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05since\x88\x01\x01B\b\n" +
	"\x06_since\"<\n" +
	"\x13PublishEventRequest\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.guild.v1.EventR\x05event\"J\n" +
	"\x14PublishEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9f\x01\n" +
	"\fEventService\x12@\n" +
	"\fStreamEvents\x12\x1d.guild.v1.StreamEventsRequest\x1a\x0f.guild.v1.Event0\x01\x12M\n" +
	"\fPublishEvent\x12\x1d.guild.v1.PublishEventRequest\x1a\x1e.guild.v1.PublishEventResponseB4Z2github.com/lancekrogers/guild/pkg/grpc/pb/guild/v1b\x06proto3"

var (
	file_proto_guild_v1_events_proto_rawDescOnce sync.Once
	file_proto_guild_v1_events_proto_rawDescData []byte
)

func file_proto_guild_v1_events_proto_rawDescGZIP() []byte {
	file_proto_guild_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_guild_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_guild_v1_events_proto_rawDesc), len(file_proto_guild_v1_events_proto_rawDesc)))
	})
	return file_proto_guild_v1_events_proto_rawDescData
}

var file_proto_guild_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_guild_v1_events_proto_goTypes = []any{
	(*Event)(nil),                 // 0: guild.v1.Event
	(*StreamEventsRequest)(nil),   // 1: guild.v1.StreamEventsRequest
	(*PublishEventRequest)(nil),   // 2: guild.v1.PublishEventRequest
	(*PublishEventResponse)(nil),  // 3: guild.v1.PublishEventResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_proto_guild_v1_events_proto_depIdxs = []int32{
	4, // 0: guild.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: guild.v1.Event.data:type_name -> google.protobuf.Struct
	4, // 2: guild.v1.StreamEventsRequest.since:type_name -> google.protobuf.Timestamp
	0, // 3: guild.v1.PublishEventRequest.event:type_name -> guild.v1.Event
	1, // 4: guild.v1.EventService.StreamEvents:input_type -> guild.v1.StreamEventsRequest
	2, // 5: guild.v1.EventService.PublishEvent:input_type -> guild.v1.PublishEventRequest
	0, // 6: guild.v1.EventService.StreamEvents:output_type -> guild.v1.Event
	3, // 7: guild.v1.EventService.PublishEvent:output_type -> guild.v1.PublishEventResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_guild_v1_events_proto_init() }
func file_proto_guild_v1_events_proto_init() {
	if File_proto_guild_v1_events_proto != nil {
		return
	}
	file_proto_guild_v1_events_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_guild_v1_events_proto_rawDesc), len(file_proto_guild_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_guild_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_guild_v1_events_proto_depIdxs,
		MessageInfos:      file_proto_guild_v1_events_proto_msgTypes,
	}.Build()
	File_proto_guild_v1_events_proto = out.File
	file_proto_guild_v1_events_proto_goTypes = nil
	file_proto_guild_v1_events_proto_depIdxs = nil
}
