// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: guild/v1/guild.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Campaign represents a strategic goal with multiple objectives
type Campaign struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ObjectiveIds        []string               `protobuf:"bytes,5,rep,name=objective_ids,json=objectiveIds,proto3" json:"objective_ids,omitempty"`
	Tags                []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Progress            float64                `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"`
	TotalObjectives     int32                  `protobuf:"varint,8,opt,name=total_objectives,json=totalObjectives,proto3" json:"total_objectives,omitempty"`
	CompletedObjectives int32                  `protobuf:"varint,9,opt,name=completed_objectives,json=completedObjectives,proto3" json:"completed_objectives,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt           int64                  `protobuf:"varint,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt         int64                  `protobuf:"varint,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_guild_v1_guild_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetObjectiveIds() []string {
	if x != nil {
		return x.ObjectiveIds
	}
	return nil
}

func (x *Campaign) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Campaign) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Campaign) GetTotalObjectives() int32 {
	if x != nil {
		return x.TotalObjectives
	}
	return 0
}

func (x *Campaign) GetCompletedObjectives() int32 {
	if x != nil {
		return x.CompletedObjectives
	}
	return 0
}

func (x *Campaign) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Campaign) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Campaign) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Campaign) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Campaign) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// WatchRequest for streaming campaign updates
type WatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CampaignId      string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"` // empty = active campaign
	IncludeAgents   bool                   `protobuf:"varint,2,opt,name=include_agents,json=includeAgents,proto3" json:"include_agents,omitempty"`
	IncludeKanban   bool                   `protobuf:"varint,3,opt,name=include_kanban,json=includeKanban,proto3" json:"include_kanban,omitempty"`
	IncludeProgress bool                   `protobuf:"varint,4,opt,name=include_progress,json=includeProgress,proto3" json:"include_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *WatchRequest) GetIncludeAgents() bool {
	if x != nil {
		return x.IncludeAgents
	}
	return false
}

func (x *WatchRequest) GetIncludeKanban() bool {
	if x != nil {
		return x.IncludeKanban
	}
	return false
}

func (x *WatchRequest) GetIncludeProgress() bool {
	if x != nil {
		return x.IncludeProgress
	}
	return false
}

// BoardUpdate contains ASCII board frame with ANSI colors
type BoardUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         string                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"` // ASCII board with ANSI colors
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *BoardMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardUpdate) Reset() {
	*x = BoardUpdate{}
	mi := &file_guild_v1_guild_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardUpdate) ProtoMessage() {}

func (x *BoardUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardUpdate.ProtoReflect.Descriptor instead.
func (*BoardUpdate) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{2}
}

func (x *BoardUpdate) GetFrame() string {
	if x != nil {
		return x.Frame
	}
	return ""
}

func (x *BoardUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BoardUpdate) GetMetadata() *BoardMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// BoardMetadata provides additional information about the board state
type BoardMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Width          int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ActiveAgents   int32                  `protobuf:"varint,3,opt,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	TotalTasks     int32                  `protobuf:"varint,4,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks int32                  `protobuf:"varint,5,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	Fps            float64                `protobuf:"fixed64,6,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BoardMetadata) Reset() {
	*x = BoardMetadata{}
	mi := &file_guild_v1_guild_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMetadata) ProtoMessage() {}

func (x *BoardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMetadata.ProtoReflect.Descriptor instead.
func (*BoardMetadata) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{3}
}

func (x *BoardMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoardMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoardMetadata) GetActiveAgents() int32 {
	if x != nil {
		return x.ActiveAgents
	}
	return 0
}

func (x *BoardMetadata) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *BoardMetadata) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *BoardMetadata) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

// Campaign management messages
type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{4}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{5}
}

func (x *ListCampaignsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCampaignsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCampaignsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{6}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *ListCampaignsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCampaignsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateCampaignRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCampaignRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateCampaignRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCampaignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCampaignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Campaign action messages
type CampaignActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignActionRequest) Reset() {
	*x = CampaignActionRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignActionRequest) ProtoMessage() {}

func (x *CampaignActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignActionRequest.ProtoReflect.Descriptor instead.
func (*CampaignActionRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{11}
}

func (x *CampaignActionRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

// Objective management messages
type AddObjectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ObjectiveId   string                 `protobuf:"bytes,2,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddObjectiveRequest) Reset() {
	*x = AddObjectiveRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddObjectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddObjectiveRequest) ProtoMessage() {}

func (x *AddObjectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddObjectiveRequest.ProtoReflect.Descriptor instead.
func (*AddObjectiveRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{12}
}

func (x *AddObjectiveRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *AddObjectiveRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

type RemoveObjectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ObjectiveId   string                 `protobuf:"bytes,2,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveObjectiveRequest) Reset() {
	*x = RemoveObjectiveRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveObjectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveObjectiveRequest) ProtoMessage() {}

func (x *RemoveObjectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveObjectiveRequest.ProtoReflect.Descriptor instead.
func (*RemoveObjectiveRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveObjectiveRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *RemoveObjectiveRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

// Error details
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_guild_v1_guild_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_guild_v1_guild_proto protoreflect.FileDescriptor

const file_guild_v1_guild_proto_rawDesc = "" +
	"\n" +
	"\x14guild/v1/guild.proto\x12\bguild.v1\"\x96\x04\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\robjective_ids\x18\x05 \x03(\tR\fobjectiveIds\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\x12)\n" +
	"\x10total_objectives\x18\b \x01(\x05R\x0ftotalObjectives\x121\n" +
	"\x14completed_objectives\x18\t \x01(\x05R\x13completedObjectives\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\f \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\r \x01(\x03R\vcompletedAt\x12<\n" +
	"\bmetadata\x18\x0e \x03(\v2 .guild.v1.Campaign.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12%\n" +
	"\x0einclude_agents\x18\x02 \x01(\bR\rincludeAgents\x12%\n" +
	"\x0einclude_kanban\x18\x03 \x01(\bR\rincludeKanban\x12)\n" +
	"\x10include_progress\x18\x04 \x01(\bR\x0fincludeProgress\"v\n" +
	"\vBoardUpdate\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\tR\x05frame\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.guild.v1.BoardMetadataR\bmetadata\"\xbe\x01\n" +
	"\rBoardMetadata\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12#\n" +
	"\ractive_agents\x18\x03 \x01(\x05R\factiveAgents\x12\x1f\n" +
	"\vtotal_tasks\x18\x04 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x05 \x01(\x05R\x0ecompletedTasks\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\x01R\x03fps\"$\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x14ListCampaignsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"\x92\x01\n" +
	"\x15ListCampaignsResponse\x120\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x12.guild.v1.CampaignR\tcampaigns\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xe9\x01\n" +
	"\x15CreateCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.guild.v1.CreateCampaignRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x15UpdateCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.guild.v1.UpdateCampaignRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteCampaignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x15CampaignActionRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"Y\n" +
	"\x13AddObjectiveRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fobjective_id\x18\x02 \x01(\tR\vobjectiveId\"\\\n" +
	"\x16RemoveObjectiveRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fobjective_id\x18\x02 \x01(\tR\vobjectiveId\"\xb9\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.guild.v1.ErrorDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc4\a\n" +
	"\x05Guild\x12@\n" +
	"\rWatchCampaign\x12\x16.guild.v1.WatchRequest\x1a\x15.guild.v1.BoardUpdate0\x01\x12?\n" +
	"\vGetCampaign\x12\x1c.guild.v1.GetCampaignRequest\x1a\x12.guild.v1.Campaign\x12P\n" +
	"\rListCampaigns\x12\x1e.guild.v1.ListCampaignsRequest\x1a\x1f.guild.v1.ListCampaignsResponse\x12E\n" +
	"\x0eCreateCampaign\x12\x1f.guild.v1.CreateCampaignRequest\x1a\x12.guild.v1.Campaign\x12E\n" +
	"\x0eUpdateCampaign\x12\x1f.guild.v1.UpdateCampaignRequest\x1a\x12.guild.v1.Campaign\x12S\n" +
	"\x0eDeleteCampaign\x12\x1f.guild.v1.DeleteCampaignRequest\x1a .guild.v1.DeleteCampaignResponse\x12D\n" +
	"\rStartCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12D\n" +
	"\rPauseCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12E\n" +
	"\x0eResumeCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12G\n" +
	"\x10CompleteCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12E\n" +
	"\x0eCancelCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12K\n" +
	"\x16AddObjectiveToCampaign\x12\x1d.guild.v1.AddObjectiveRequest\x1a\x12.guild.v1.Campaign\x12S\n" +
	"\x1bRemoveObjectiveFromCampaign\x12 .guild.v1.RemoveObjectiveRequest\x1a\x12.guild.v1.CampaignB2Z0github.com/guild-ventures/guild-core/pkg/grpc/pbb\x06proto3"

var (
	file_guild_v1_guild_proto_rawDescOnce sync.Once
	file_guild_v1_guild_proto_rawDescData []byte
)

func file_guild_v1_guild_proto_rawDescGZIP() []byte {
	file_guild_v1_guild_proto_rawDescOnce.Do(func() {
		file_guild_v1_guild_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_v1_guild_proto_rawDesc), len(file_guild_v1_guild_proto_rawDesc)))
	})
	return file_guild_v1_guild_proto_rawDescData
}

var file_guild_v1_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_guild_v1_guild_proto_goTypes = []any{
	(*Campaign)(nil),               // 0: guild.v1.Campaign
	(*WatchRequest)(nil),           // 1: guild.v1.WatchRequest
	(*BoardUpdate)(nil),            // 2: guild.v1.BoardUpdate
	(*BoardMetadata)(nil),          // 3: guild.v1.BoardMetadata
	(*GetCampaignRequest)(nil),     // 4: guild.v1.GetCampaignRequest
	(*ListCampaignsRequest)(nil),   // 5: guild.v1.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),  // 6: guild.v1.ListCampaignsResponse
	(*CreateCampaignRequest)(nil),  // 7: guild.v1.CreateCampaignRequest
	(*UpdateCampaignRequest)(nil),  // 8: guild.v1.UpdateCampaignRequest
	(*DeleteCampaignRequest)(nil),  // 9: guild.v1.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil), // 10: guild.v1.DeleteCampaignResponse
	(*CampaignActionRequest)(nil),  // 11: guild.v1.CampaignActionRequest
	(*AddObjectiveRequest)(nil),    // 12: guild.v1.AddObjectiveRequest
	(*RemoveObjectiveRequest)(nil), // 13: guild.v1.RemoveObjectiveRequest
	(*ErrorDetail)(nil),            // 14: guild.v1.ErrorDetail
	nil,                            // 15: guild.v1.Campaign.MetadataEntry
	nil,                            // 16: guild.v1.CreateCampaignRequest.MetadataEntry
	nil,                            // 17: guild.v1.UpdateCampaignRequest.MetadataEntry
	nil,                            // 18: guild.v1.ErrorDetail.MetadataEntry
}
var file_guild_v1_guild_proto_depIdxs = []int32{
	15, // 0: guild.v1.Campaign.metadata:type_name -> guild.v1.Campaign.MetadataEntry
	3,  // 1: guild.v1.BoardUpdate.metadata:type_name -> guild.v1.BoardMetadata
	0,  // 2: guild.v1.ListCampaignsResponse.campaigns:type_name -> guild.v1.Campaign
	16, // 3: guild.v1.CreateCampaignRequest.metadata:type_name -> guild.v1.CreateCampaignRequest.MetadataEntry
	17, // 4: guild.v1.UpdateCampaignRequest.metadata:type_name -> guild.v1.UpdateCampaignRequest.MetadataEntry
	18, // 5: guild.v1.ErrorDetail.metadata:type_name -> guild.v1.ErrorDetail.MetadataEntry
	1,  // 6: guild.v1.Guild.WatchCampaign:input_type -> guild.v1.WatchRequest
	4,  // 7: guild.v1.Guild.GetCampaign:input_type -> guild.v1.GetCampaignRequest
	5,  // 8: guild.v1.Guild.ListCampaigns:input_type -> guild.v1.ListCampaignsRequest
	7,  // 9: guild.v1.Guild.CreateCampaign:input_type -> guild.v1.CreateCampaignRequest
	8,  // 10: guild.v1.Guild.UpdateCampaign:input_type -> guild.v1.UpdateCampaignRequest
	9,  // 11: guild.v1.Guild.DeleteCampaign:input_type -> guild.v1.DeleteCampaignRequest
	11, // 12: guild.v1.Guild.StartCampaign:input_type -> guild.v1.CampaignActionRequest
	11, // 13: guild.v1.Guild.PauseCampaign:input_type -> guild.v1.CampaignActionRequest
	11, // 14: guild.v1.Guild.ResumeCampaign:input_type -> guild.v1.CampaignActionRequest
	11, // 15: guild.v1.Guild.CompleteCampaign:input_type -> guild.v1.CampaignActionRequest
	11, // 16: guild.v1.Guild.CancelCampaign:input_type -> guild.v1.CampaignActionRequest
	12, // 17: guild.v1.Guild.AddObjectiveToCampaign:input_type -> guild.v1.AddObjectiveRequest
	13, // 18: guild.v1.Guild.RemoveObjectiveFromCampaign:input_type -> guild.v1.RemoveObjectiveRequest
	2,  // 19: guild.v1.Guild.WatchCampaign:output_type -> guild.v1.BoardUpdate
	0,  // 20: guild.v1.Guild.GetCampaign:output_type -> guild.v1.Campaign
	6,  // 21: guild.v1.Guild.ListCampaigns:output_type -> guild.v1.ListCampaignsResponse
	0,  // 22: guild.v1.Guild.CreateCampaign:output_type -> guild.v1.Campaign
	0,  // 23: guild.v1.Guild.UpdateCampaign:output_type -> guild.v1.Campaign
	10, // 24: guild.v1.Guild.DeleteCampaign:output_type -> guild.v1.DeleteCampaignResponse
	0,  // 25: guild.v1.Guild.StartCampaign:output_type -> guild.v1.Campaign
	0,  // 26: guild.v1.Guild.PauseCampaign:output_type -> guild.v1.Campaign
	0,  // 27: guild.v1.Guild.ResumeCampaign:output_type -> guild.v1.Campaign
	0,  // 28: guild.v1.Guild.CompleteCampaign:output_type -> guild.v1.Campaign
	0,  // 29: guild.v1.Guild.CancelCampaign:output_type -> guild.v1.Campaign
	0,  // 30: guild.v1.Guild.AddObjectiveToCampaign:output_type -> guild.v1.Campaign
	0,  // 31: guild.v1.Guild.RemoveObjectiveFromCampaign:output_type -> guild.v1.Campaign
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_guild_v1_guild_proto_init() }
func file_guild_v1_guild_proto_init() {
	if File_guild_v1_guild_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_v1_guild_proto_rawDesc), len(file_guild_v1_guild_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guild_v1_guild_proto_goTypes,
		DependencyIndexes: file_guild_v1_guild_proto_depIdxs,
		MessageInfos:      file_guild_v1_guild_proto_msgTypes,
	}.Build()
	File_guild_v1_guild_proto = out.File
	file_guild_v1_guild_proto_goTypes = nil
	file_guild_v1_guild_proto_depIdxs = nil
}
