// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/guild/v1/guild.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Guild_WatchCampaign_FullMethodName                = "/guild.v1.Guild/WatchCampaign"
	Guild_GetCampaign_FullMethodName                  = "/guild.v1.Guild/GetCampaign"
	Guild_ListCampaigns_FullMethodName                = "/guild.v1.Guild/ListCampaigns"
	Guild_CreateCampaign_FullMethodName               = "/guild.v1.Guild/CreateCampaign"
	Guild_UpdateCampaign_FullMethodName               = "/guild.v1.Guild/UpdateCampaign"
	Guild_DeleteCampaign_FullMethodName               = "/guild.v1.Guild/DeleteCampaign"
	Guild_StartPlanningCampaign_FullMethodName        = "/guild.v1.Guild/StartPlanningCampaign"
	Guild_MarkCampaignReady_FullMethodName            = "/guild.v1.Guild/MarkCampaignReady"
	Guild_StartCampaign_FullMethodName                = "/guild.v1.Guild/StartCampaign"
	Guild_PauseCampaign_FullMethodName                = "/guild.v1.Guild/PauseCampaign"
	Guild_ResumeCampaign_FullMethodName               = "/guild.v1.Guild/ResumeCampaign"
	Guild_CompleteCampaign_FullMethodName             = "/guild.v1.Guild/CompleteCampaign"
	Guild_CancelCampaign_FullMethodName               = "/guild.v1.Guild/CancelCampaign"
	Guild_AddCommissionToCampaign_FullMethodName      = "/guild.v1.Guild/AddCommissionToCampaign"
	Guild_RemoveCommissionFromCampaign_FullMethodName = "/guild.v1.Guild/RemoveCommissionFromCampaign"
	Guild_SendMessageToAgent_FullMethodName           = "/guild.v1.Guild/SendMessageToAgent"
	Guild_StreamAgentConversation_FullMethodName      = "/guild.v1.Guild/StreamAgentConversation"
	Guild_ListAvailableAgents_FullMethodName          = "/guild.v1.Guild/ListAvailableAgents"
	Guild_GetAgentStatus_FullMethodName               = "/guild.v1.Guild/GetAgentStatus"
)

// GuildClient is the client API for Guild service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Guild service provides API for managing campaigns and monitoring their progress
type GuildClient interface {
	// WatchCampaign streams live dashboard updates for a campaign
	WatchCampaign(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BoardUpdate], error)
	// Campaign management
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error)
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignResponse, error)
	// Campaign state transitions
	StartPlanningCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	MarkCampaignReady(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	StartCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	PauseCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	ResumeCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	CompleteCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	CancelCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error)
	// Commission management
	AddCommissionToCampaign(ctx context.Context, in *AddCommissionRequest, opts ...grpc.CallOption) (*Campaign, error)
	RemoveCommissionFromCampaign(ctx context.Context, in *RemoveCommissionRequest, opts ...grpc.CallOption) (*Campaign, error)
	// Agent communication
	SendMessageToAgent(ctx context.Context, in *AgentMessageRequest, opts ...grpc.CallOption) (*AgentMessageResponse, error)
	StreamAgentConversation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentStreamRequest, AgentStreamResponse], error)
	ListAvailableAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*AgentStatus, error)
}

type guildClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildClient(cc grpc.ClientConnInterface) GuildClient {
	return &guildClient{cc}
}

func (c *guildClient) WatchCampaign(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BoardUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Guild_ServiceDesc.Streams[0], Guild_WatchCampaign_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, BoardUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Guild_WatchCampaignClient = grpc.ServerStreamingClient[BoardUpdate]

func (c *guildClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignsResponse)
	err := c.cc.Invoke(ctx, Guild_ListCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_UpdateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCampaignResponse)
	err := c.cc.Invoke(ctx, Guild_DeleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) StartPlanningCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_StartPlanningCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) MarkCampaignReady(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_MarkCampaignReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) StartCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_StartCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) PauseCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_PauseCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) ResumeCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_ResumeCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) CompleteCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_CompleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) CancelCampaign(ctx context.Context, in *CampaignActionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_CancelCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) AddCommissionToCampaign(ctx context.Context, in *AddCommissionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_AddCommissionToCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) RemoveCommissionFromCampaign(ctx context.Context, in *RemoveCommissionRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, Guild_RemoveCommissionFromCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) SendMessageToAgent(ctx context.Context, in *AgentMessageRequest, opts ...grpc.CallOption) (*AgentMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentMessageResponse)
	err := c.cc.Invoke(ctx, Guild_SendMessageToAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) StreamAgentConversation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentStreamRequest, AgentStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Guild_ServiceDesc.Streams[1], Guild_StreamAgentConversation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentStreamRequest, AgentStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Guild_StreamAgentConversationClient = grpc.BidiStreamingClient[AgentStreamRequest, AgentStreamResponse]

func (c *guildClient) ListAvailableAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, Guild_ListAvailableAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*AgentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, Guild_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildServer is the server API for Guild service.
// All implementations must embed UnimplementedGuildServer
// for forward compatibility.
//
// Guild service provides API for managing campaigns and monitoring their progress
type GuildServer interface {
	// WatchCampaign streams live dashboard updates for a campaign
	WatchCampaign(*WatchRequest, grpc.ServerStreamingServer[BoardUpdate]) error
	// Campaign management
	GetCampaign(context.Context, *GetCampaignRequest) (*Campaign, error)
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	CreateCampaign(context.Context, *CreateCampaignRequest) (*Campaign, error)
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*Campaign, error)
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignResponse, error)
	// Campaign state transitions
	StartPlanningCampaign(context.Context, *CampaignActionRequest) (*Campaign, error)
	MarkCampaignReady(context.Context, *CampaignActionRequest) (*Campaign, error)
	StartCampaign(context.Context, *CampaignActionRequest) (*Campaign, error)
	PauseCampaign(context.Context, *CampaignActionRequest) (*Campaign, error)
	ResumeCampaign(context.Context, *CampaignActionRequest) (*Campaign, error)
	CompleteCampaign(context.Context, *CampaignActionRequest) (*Campaign, error)
	CancelCampaign(context.Context, *CampaignActionRequest) (*Campaign, error)
	// Commission management
	AddCommissionToCampaign(context.Context, *AddCommissionRequest) (*Campaign, error)
	RemoveCommissionFromCampaign(context.Context, *RemoveCommissionRequest) (*Campaign, error)
	// Agent communication
	SendMessageToAgent(context.Context, *AgentMessageRequest) (*AgentMessageResponse, error)
	StreamAgentConversation(grpc.BidiStreamingServer[AgentStreamRequest, AgentStreamResponse]) error
	ListAvailableAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*AgentStatus, error)
	mustEmbedUnimplementedGuildServer()
}

// UnimplementedGuildServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildServer struct{}

func (UnimplementedGuildServer) WatchCampaign(*WatchRequest, grpc.ServerStreamingServer[BoardUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method WatchCampaign not implemented")
}
func (UnimplementedGuildServer) GetCampaign(context.Context, *GetCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedGuildServer) ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (UnimplementedGuildServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedGuildServer) UpdateCampaign(context.Context, *UpdateCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCampaign not implemented")
}
func (UnimplementedGuildServer) DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCampaign not implemented")
}
func (UnimplementedGuildServer) StartPlanningCampaign(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPlanningCampaign not implemented")
}
func (UnimplementedGuildServer) MarkCampaignReady(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkCampaignReady not implemented")
}
func (UnimplementedGuildServer) StartCampaign(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCampaign not implemented")
}
func (UnimplementedGuildServer) PauseCampaign(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseCampaign not implemented")
}
func (UnimplementedGuildServer) ResumeCampaign(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeCampaign not implemented")
}
func (UnimplementedGuildServer) CompleteCampaign(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteCampaign not implemented")
}
func (UnimplementedGuildServer) CancelCampaign(context.Context, *CampaignActionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCampaign not implemented")
}
func (UnimplementedGuildServer) AddCommissionToCampaign(context.Context, *AddCommissionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommissionToCampaign not implemented")
}
func (UnimplementedGuildServer) RemoveCommissionFromCampaign(context.Context, *RemoveCommissionRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCommissionFromCampaign not implemented")
}
func (UnimplementedGuildServer) SendMessageToAgent(context.Context, *AgentMessageRequest) (*AgentMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToAgent not implemented")
}
func (UnimplementedGuildServer) StreamAgentConversation(grpc.BidiStreamingServer[AgentStreamRequest, AgentStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAgentConversation not implemented")
}
func (UnimplementedGuildServer) ListAvailableAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableAgents not implemented")
}
func (UnimplementedGuildServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*AgentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedGuildServer) mustEmbedUnimplementedGuildServer() {}
func (UnimplementedGuildServer) testEmbeddedByValue()               {}

// UnsafeGuildServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildServer will
// result in compilation errors.
type UnsafeGuildServer interface {
	mustEmbedUnimplementedGuildServer()
}

func RegisterGuildServer(s grpc.ServiceRegistrar, srv GuildServer) {
	// If the following call pancis, it indicates UnimplementedGuildServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Guild_ServiceDesc, srv)
}

func _Guild_WatchCampaign_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuildServer).WatchCampaign(m, &grpc.GenericServerStream[WatchRequest, BoardUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Guild_WatchCampaignServer = grpc.ServerStreamingServer[BoardUpdate]

func _Guild_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_ListCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_UpdateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).UpdateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_UpdateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_DeleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).DeleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_DeleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_StartPlanningCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).StartPlanningCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_StartPlanningCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).StartPlanningCampaign(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_MarkCampaignReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).MarkCampaignReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_MarkCampaignReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).MarkCampaignReady(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_StartCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).StartCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_StartCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).StartCampaign(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_PauseCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).PauseCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_PauseCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).PauseCampaign(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_ResumeCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).ResumeCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_ResumeCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).ResumeCampaign(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_CompleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).CompleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_CompleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).CompleteCampaign(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_CancelCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).CancelCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_CancelCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).CancelCampaign(ctx, req.(*CampaignActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_AddCommissionToCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).AddCommissionToCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_AddCommissionToCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).AddCommissionToCampaign(ctx, req.(*AddCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_RemoveCommissionFromCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCommissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).RemoveCommissionFromCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_RemoveCommissionFromCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).RemoveCommissionFromCampaign(ctx, req.(*RemoveCommissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_SendMessageToAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).SendMessageToAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_SendMessageToAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).SendMessageToAgent(ctx, req.(*AgentMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_StreamAgentConversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuildServer).StreamAgentConversation(&grpc.GenericServerStream[AgentStreamRequest, AgentStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Guild_StreamAgentConversationServer = grpc.BidiStreamingServer[AgentStreamRequest, AgentStreamResponse]

func _Guild_ListAvailableAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).ListAvailableAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_ListAvailableAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).ListAvailableAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Guild_ServiceDesc is the grpc.ServiceDesc for Guild service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Guild_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guild.v1.Guild",
	HandlerType: (*GuildServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCampaign",
			Handler:    _Guild_GetCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _Guild_ListCampaigns_Handler,
		},
		{
			MethodName: "CreateCampaign",
			Handler:    _Guild_CreateCampaign_Handler,
		},
		{
			MethodName: "UpdateCampaign",
			Handler:    _Guild_UpdateCampaign_Handler,
		},
		{
			MethodName: "DeleteCampaign",
			Handler:    _Guild_DeleteCampaign_Handler,
		},
		{
			MethodName: "StartPlanningCampaign",
			Handler:    _Guild_StartPlanningCampaign_Handler,
		},
		{
			MethodName: "MarkCampaignReady",
			Handler:    _Guild_MarkCampaignReady_Handler,
		},
		{
			MethodName: "StartCampaign",
			Handler:    _Guild_StartCampaign_Handler,
		},
		{
			MethodName: "PauseCampaign",
			Handler:    _Guild_PauseCampaign_Handler,
		},
		{
			MethodName: "ResumeCampaign",
			Handler:    _Guild_ResumeCampaign_Handler,
		},
		{
			MethodName: "CompleteCampaign",
			Handler:    _Guild_CompleteCampaign_Handler,
		},
		{
			MethodName: "CancelCampaign",
			Handler:    _Guild_CancelCampaign_Handler,
		},
		{
			MethodName: "AddCommissionToCampaign",
			Handler:    _Guild_AddCommissionToCampaign_Handler,
		},
		{
			MethodName: "RemoveCommissionFromCampaign",
			Handler:    _Guild_RemoveCommissionFromCampaign_Handler,
		},
		{
			MethodName: "SendMessageToAgent",
			Handler:    _Guild_SendMessageToAgent_Handler,
		},
		{
			MethodName: "ListAvailableAgents",
			Handler:    _Guild_ListAvailableAgents_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _Guild_GetAgentStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCampaign",
			Handler:       _Guild_WatchCampaign_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAgentConversation",
			Handler:       _Guild_StreamAgentConversation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/guild/v1/guild.proto",
}
