// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: guild/v1/guild.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamControl_Command int32

const (
	StreamControl_START  StreamControl_Command = 0
	StreamControl_STOP   StreamControl_Command = 1
	StreamControl_PAUSE  StreamControl_Command = 2
	StreamControl_RESUME StreamControl_Command = 3
)

// Enum value maps for StreamControl_Command.
var (
	StreamControl_Command_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "PAUSE",
		3: "RESUME",
	}
	StreamControl_Command_value = map[string]int32{
		"START":  0,
		"STOP":   1,
		"PAUSE":  2,
		"RESUME": 3,
	}
)

func (x StreamControl_Command) Enum() *StreamControl_Command {
	p := new(StreamControl_Command)
	*p = x
	return p
}

func (x StreamControl_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamControl_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_v1_guild_proto_enumTypes[0].Descriptor()
}

func (StreamControl_Command) Type() protoreflect.EnumType {
	return &file_guild_v1_guild_proto_enumTypes[0]
}

func (x StreamControl_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamControl_Command.Descriptor instead.
func (StreamControl_Command) EnumDescriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{20, 0}
}

type StreamEvent_EventType int32

const (
	StreamEvent_AGENT_THINKING              StreamEvent_EventType = 0
	StreamEvent_AGENT_WORKING               StreamEvent_EventType = 1
	StreamEvent_TOOL_EXECUTING              StreamEvent_EventType = 2
	StreamEvent_MEMORY_RETRIEVING           StreamEvent_EventType = 3
	StreamEvent_ERROR                       StreamEvent_EventType = 4
	StreamEvent_TOOL_DISCOVERY              StreamEvent_EventType = 5
	StreamEvent_TOOL_EXECUTION_START        StreamEvent_EventType = 6
	StreamEvent_TOOL_EXECUTION_PROGRESS     StreamEvent_EventType = 7
	StreamEvent_TOOL_EXECUTION_COMPLETE     StreamEvent_EventType = 8
	StreamEvent_TOOL_AUTHORIZATION_REQUIRED StreamEvent_EventType = 9
)

// Enum value maps for StreamEvent_EventType.
var (
	StreamEvent_EventType_name = map[int32]string{
		0: "AGENT_THINKING",
		1: "AGENT_WORKING",
		2: "TOOL_EXECUTING",
		3: "MEMORY_RETRIEVING",
		4: "ERROR",
		5: "TOOL_DISCOVERY",
		6: "TOOL_EXECUTION_START",
		7: "TOOL_EXECUTION_PROGRESS",
		8: "TOOL_EXECUTION_COMPLETE",
		9: "TOOL_AUTHORIZATION_REQUIRED",
	}
	StreamEvent_EventType_value = map[string]int32{
		"AGENT_THINKING":              0,
		"AGENT_WORKING":               1,
		"TOOL_EXECUTING":              2,
		"MEMORY_RETRIEVING":           3,
		"ERROR":                       4,
		"TOOL_DISCOVERY":              5,
		"TOOL_EXECUTION_START":        6,
		"TOOL_EXECUTION_PROGRESS":     7,
		"TOOL_EXECUTION_COMPLETE":     8,
		"TOOL_AUTHORIZATION_REQUIRED": 9,
	}
)

func (x StreamEvent_EventType) Enum() *StreamEvent_EventType {
	p := new(StreamEvent_EventType)
	*p = x
	return p
}

func (x StreamEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_v1_guild_proto_enumTypes[1].Descriptor()
}

func (StreamEvent_EventType) Type() protoreflect.EnumType {
	return &file_guild_v1_guild_proto_enumTypes[1]
}

func (x StreamEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamEvent_EventType.Descriptor instead.
func (StreamEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{21, 0}
}

type AgentStatus_State int32

const (
	AgentStatus_IDLE     AgentStatus_State = 0
	AgentStatus_THINKING AgentStatus_State = 1
	AgentStatus_WORKING  AgentStatus_State = 2
	AgentStatus_WAITING  AgentStatus_State = 3
	AgentStatus_ERROR    AgentStatus_State = 4
	AgentStatus_OFFLINE  AgentStatus_State = 5
)

// Enum value maps for AgentStatus_State.
var (
	AgentStatus_State_name = map[int32]string{
		0: "IDLE",
		1: "THINKING",
		2: "WORKING",
		3: "WAITING",
		4: "ERROR",
		5: "OFFLINE",
	}
	AgentStatus_State_value = map[string]int32{
		"IDLE":     0,
		"THINKING": 1,
		"WORKING":  2,
		"WAITING":  3,
		"ERROR":    4,
		"OFFLINE":  5,
	}
)

func (x AgentStatus_State) Enum() *AgentStatus_State {
	p := new(AgentStatus_State)
	*p = x
	return p
}

func (x AgentStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_v1_guild_proto_enumTypes[2].Descriptor()
}

func (AgentStatus_State) Type() protoreflect.EnumType {
	return &file_guild_v1_guild_proto_enumTypes[2]
}

func (x AgentStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus_State.Descriptor instead.
func (AgentStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{27, 0}
}

// Campaign represents a strategic goal with multiple objectives
type Campaign struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ObjectiveIds        []string               `protobuf:"bytes,5,rep,name=objective_ids,json=objectiveIds,proto3" json:"objective_ids,omitempty"`
	Tags                []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Progress            float64                `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"`
	TotalObjectives     int32                  `protobuf:"varint,8,opt,name=total_objectives,json=totalObjectives,proto3" json:"total_objectives,omitempty"`
	CompletedObjectives int32                  `protobuf:"varint,9,opt,name=completed_objectives,json=completedObjectives,proto3" json:"completed_objectives,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt           int64                  `protobuf:"varint,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt         int64                  `protobuf:"varint,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_guild_v1_guild_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetObjectiveIds() []string {
	if x != nil {
		return x.ObjectiveIds
	}
	return nil
}

func (x *Campaign) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Campaign) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Campaign) GetTotalObjectives() int32 {
	if x != nil {
		return x.TotalObjectives
	}
	return 0
}

func (x *Campaign) GetCompletedObjectives() int32 {
	if x != nil {
		return x.CompletedObjectives
	}
	return 0
}

func (x *Campaign) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Campaign) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Campaign) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Campaign) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Campaign) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// WatchRequest for streaming campaign updates
type WatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CampaignId      string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"` // empty = active campaign
	IncludeAgents   bool                   `protobuf:"varint,2,opt,name=include_agents,json=includeAgents,proto3" json:"include_agents,omitempty"`
	IncludeKanban   bool                   `protobuf:"varint,3,opt,name=include_kanban,json=includeKanban,proto3" json:"include_kanban,omitempty"`
	IncludeProgress bool                   `protobuf:"varint,4,opt,name=include_progress,json=includeProgress,proto3" json:"include_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *WatchRequest) GetIncludeAgents() bool {
	if x != nil {
		return x.IncludeAgents
	}
	return false
}

func (x *WatchRequest) GetIncludeKanban() bool {
	if x != nil {
		return x.IncludeKanban
	}
	return false
}

func (x *WatchRequest) GetIncludeProgress() bool {
	if x != nil {
		return x.IncludeProgress
	}
	return false
}

// BoardUpdate contains ASCII board frame with ANSI colors
type BoardUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         string                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"` // ASCII board with ANSI colors
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *BoardMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardUpdate) Reset() {
	*x = BoardUpdate{}
	mi := &file_guild_v1_guild_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardUpdate) ProtoMessage() {}

func (x *BoardUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardUpdate.ProtoReflect.Descriptor instead.
func (*BoardUpdate) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{2}
}

func (x *BoardUpdate) GetFrame() string {
	if x != nil {
		return x.Frame
	}
	return ""
}

func (x *BoardUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BoardUpdate) GetMetadata() *BoardMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// BoardMetadata provides additional information about the board state
type BoardMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Width          int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ActiveAgents   int32                  `protobuf:"varint,3,opt,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	TotalTasks     int32                  `protobuf:"varint,4,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks int32                  `protobuf:"varint,5,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	Fps            float64                `protobuf:"fixed64,6,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BoardMetadata) Reset() {
	*x = BoardMetadata{}
	mi := &file_guild_v1_guild_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardMetadata) ProtoMessage() {}

func (x *BoardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardMetadata.ProtoReflect.Descriptor instead.
func (*BoardMetadata) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{3}
}

func (x *BoardMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoardMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoardMetadata) GetActiveAgents() int32 {
	if x != nil {
		return x.ActiveAgents
	}
	return 0
}

func (x *BoardMetadata) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *BoardMetadata) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *BoardMetadata) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

// Campaign management messages
type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{4}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{5}
}

func (x *ListCampaignsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCampaignsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCampaignsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{6}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *ListCampaignsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCampaignsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateCampaignRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCampaignRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateCampaignRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCampaignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCampaignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Campaign action messages
type CampaignActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignActionRequest) Reset() {
	*x = CampaignActionRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignActionRequest) ProtoMessage() {}

func (x *CampaignActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignActionRequest.ProtoReflect.Descriptor instead.
func (*CampaignActionRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{11}
}

func (x *CampaignActionRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

// Objective management messages
type AddObjectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ObjectiveId   string                 `protobuf:"bytes,2,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddObjectiveRequest) Reset() {
	*x = AddObjectiveRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddObjectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddObjectiveRequest) ProtoMessage() {}

func (x *AddObjectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddObjectiveRequest.ProtoReflect.Descriptor instead.
func (*AddObjectiveRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{12}
}

func (x *AddObjectiveRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *AddObjectiveRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

type RemoveObjectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ObjectiveId   string                 `protobuf:"bytes,2,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveObjectiveRequest) Reset() {
	*x = RemoveObjectiveRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveObjectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveObjectiveRequest) ProtoMessage() {}

func (x *RemoveObjectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveObjectiveRequest.ProtoReflect.Descriptor instead.
func (*RemoveObjectiveRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveObjectiveRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *RemoveObjectiveRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

// Error details
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_guild_v1_guild_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Agent communication messages
type AgentMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CampaignId    string                 `protobuf:"bytes,4,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageRequest) Reset() {
	*x = AgentMessageRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageRequest) ProtoMessage() {}

func (x *AgentMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageRequest.ProtoReflect.Descriptor instead.
func (*AgentMessageRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{15}
}

func (x *AgentMessageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentMessageRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *AgentMessageRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type AgentMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        *AgentStatus           `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageResponse) Reset() {
	*x = AgentMessageResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageResponse) ProtoMessage() {}

func (x *AgentMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageResponse.ProtoReflect.Descriptor instead.
func (*AgentMessageResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{16}
}

func (x *AgentMessageResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessageResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AgentMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessageResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentMessageResponse) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Streaming agent communication
type AgentStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*AgentStreamRequest_Message
	//	*AgentStreamRequest_Control
	Request       isAgentStreamRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamRequest) Reset() {
	*x = AgentStreamRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamRequest) ProtoMessage() {}

func (x *AgentStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamRequest.ProtoReflect.Descriptor instead.
func (*AgentStreamRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{17}
}

func (x *AgentStreamRequest) GetRequest() isAgentStreamRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AgentStreamRequest) GetMessage() *AgentMessageRequest {
	if x != nil {
		if x, ok := x.Request.(*AgentStreamRequest_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *AgentStreamRequest) GetControl() *StreamControl {
	if x != nil {
		if x, ok := x.Request.(*AgentStreamRequest_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isAgentStreamRequest_Request interface {
	isAgentStreamRequest_Request()
}

type AgentStreamRequest_Message struct {
	Message *AgentMessageRequest `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type AgentStreamRequest_Control struct {
	Control *StreamControl `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*AgentStreamRequest_Message) isAgentStreamRequest_Request() {}

func (*AgentStreamRequest_Control) isAgentStreamRequest_Request() {}

type AgentStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*AgentStreamResponse_Fragment
	//	*AgentStreamResponse_Status
	//	*AgentStreamResponse_Event
	Response      isAgentStreamResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamResponse) Reset() {
	*x = AgentStreamResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamResponse) ProtoMessage() {}

func (x *AgentStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamResponse.ProtoReflect.Descriptor instead.
func (*AgentStreamResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{18}
}

func (x *AgentStreamResponse) GetResponse() isAgentStreamResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AgentStreamResponse) GetFragment() *AgentMessageFragment {
	if x != nil {
		if x, ok := x.Response.(*AgentStreamResponse_Fragment); ok {
			return x.Fragment
		}
	}
	return nil
}

func (x *AgentStreamResponse) GetStatus() *AgentStatus {
	if x != nil {
		if x, ok := x.Response.(*AgentStreamResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentStreamResponse) GetEvent() *StreamEvent {
	if x != nil {
		if x, ok := x.Response.(*AgentStreamResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentStreamResponse_Response interface {
	isAgentStreamResponse_Response()
}

type AgentStreamResponse_Fragment struct {
	Fragment *AgentMessageFragment `protobuf:"bytes,1,opt,name=fragment,proto3,oneof"`
}

type AgentStreamResponse_Status struct {
	Status *AgentStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type AgentStreamResponse_Event struct {
	Event *StreamEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*AgentStreamResponse_Fragment) isAgentStreamResponse_Response() {}

func (*AgentStreamResponse_Status) isAgentStreamResponse_Response() {}

func (*AgentStreamResponse_Event) isAgentStreamResponse_Response() {}

type AgentMessageFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsComplete    bool                   `protobuf:"varint,3,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageFragment) Reset() {
	*x = AgentMessageFragment{}
	mi := &file_guild_v1_guild_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageFragment) ProtoMessage() {}

func (x *AgentMessageFragment) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageFragment.ProtoReflect.Descriptor instead.
func (*AgentMessageFragment) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{19}
}

func (x *AgentMessageFragment) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessageFragment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMessageFragment) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *AgentMessageFragment) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessageFragment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StreamControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       StreamControl_Command  `protobuf:"varint,1,opt,name=command,proto3,enum=guild.v1.StreamControl_Command" json:"command,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControl) Reset() {
	*x = StreamControl{}
	mi := &file_guild_v1_guild_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControl) ProtoMessage() {}

func (x *StreamControl) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControl.ProtoReflect.Descriptor instead.
func (*StreamControl) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{20}
}

func (x *StreamControl) GetCommand() StreamControl_Command {
	if x != nil {
		return x.Command
	}
	return StreamControl_START
}

func (x *StreamControl) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StreamEvent_EventType  `protobuf:"varint,1,opt,name=type,proto3,enum=guild.v1.StreamEvent_EventType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ToolExecution *ToolExecution         `protobuf:"bytes,4,opt,name=tool_execution,json=toolExecution,proto3" json:"tool_execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_guild_v1_guild_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{21}
}

func (x *StreamEvent) GetType() StreamEvent_EventType {
	if x != nil {
		return x.Type
	}
	return StreamEvent_AGENT_THINKING
}

func (x *StreamEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StreamEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamEvent) GetToolExecution() *ToolExecution {
	if x != nil {
		return x.ToolExecution
	}
	return nil
}

// Tool execution details
type ToolExecution struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ToolId              string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolName            string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Parameters          map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Progress            float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	Result              string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Error               string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt           int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt         int64                  `protobuf:"varint,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	EstimatedCost       float64                `protobuf:"fixed64,10,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,11,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ToolExecution) Reset() {
	*x = ToolExecution{}
	mi := &file_guild_v1_guild_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecution) ProtoMessage() {}

func (x *ToolExecution) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecution.ProtoReflect.Descriptor instead.
func (*ToolExecution) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{22}
}

func (x *ToolExecution) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolExecution) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolExecution) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ToolExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolExecution) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ToolExecution) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolExecution) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ToolExecution) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *ToolExecution) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *ToolExecution) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

// Agent listing and status
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	IncludeStatus bool                   `protobuf:"varint,2,opt,name=include_status,json=includeStatus,proto3" json:"include_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{23}
}

func (x *ListAgentsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ListAgentsRequest) GetIncludeStatus() bool {
	if x != nil {
		return x.IncludeStatus
	}
	return false
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{24}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // manager, worker, specialist
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_guild_v1_guild_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{25}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentInfo) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AgentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{26}
}

func (x *GetAgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentStatusRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         AgentStatus_State      `protobuf:"varint,1,opt,name=state,proto3,enum=guild.v1.AgentStatus_State" json:"state,omitempty"`
	CurrentTask   string                 `protobuf:"bytes,2,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	LastActivity  int64                  `protobuf:"varint,3,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_guild_v1_guild_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{27}
}

func (x *AgentStatus) GetState() AgentStatus_State {
	if x != nil {
		return x.State
	}
	return AgentStatus_IDLE
}

func (x *AgentStatus) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *AgentStatus) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *AgentStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_guild_v1_guild_proto protoreflect.FileDescriptor

const file_guild_v1_guild_proto_rawDesc = "" +
	"\n" +
	"\x14guild/v1/guild.proto\x12\bguild.v1\"\x96\x04\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\robjective_ids\x18\x05 \x03(\tR\fobjectiveIds\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\x12)\n" +
	"\x10total_objectives\x18\b \x01(\x05R\x0ftotalObjectives\x121\n" +
	"\x14completed_objectives\x18\t \x01(\x05R\x13completedObjectives\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\f \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\r \x01(\x03R\vcompletedAt\x12<\n" +
	"\bmetadata\x18\x0e \x03(\v2 .guild.v1.Campaign.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12%\n" +
	"\x0einclude_agents\x18\x02 \x01(\bR\rincludeAgents\x12%\n" +
	"\x0einclude_kanban\x18\x03 \x01(\bR\rincludeKanban\x12)\n" +
	"\x10include_progress\x18\x04 \x01(\bR\x0fincludeProgress\"v\n" +
	"\vBoardUpdate\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\tR\x05frame\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.guild.v1.BoardMetadataR\bmetadata\"\xbe\x01\n" +
	"\rBoardMetadata\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12#\n" +
	"\ractive_agents\x18\x03 \x01(\x05R\factiveAgents\x12\x1f\n" +
	"\vtotal_tasks\x18\x04 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x05 \x01(\x05R\x0ecompletedTasks\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\x01R\x03fps\"$\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x14ListCampaignsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"\x92\x01\n" +
	"\x15ListCampaignsResponse\x120\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x12.guild.v1.CampaignR\tcampaigns\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xe9\x01\n" +
	"\x15CreateCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.guild.v1.CreateCampaignRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x15UpdateCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.guild.v1.UpdateCampaignRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteCampaignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x15CampaignActionRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"Y\n" +
	"\x13AddObjectiveRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fobjective_id\x18\x02 \x01(\tR\vobjectiveId\"\\\n" +
	"\x16RemoveObjectiveRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fobjective_id\x18\x02 \x01(\tR\vobjectiveId\"\xb9\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.guild.v1.ErrorDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x13AgentMessageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vcampaign_id\x18\x04 \x01(\tR\n" +
	"campaignId\x12D\n" +
	"\acontext\x18\x05 \x03(\v2*.guild.v1.AgentMessageRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x02\n" +
	"\x14AgentMessageResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.guild.v1.AgentMessageResponse.MetadataEntryR\bmetadata\x12-\n" +
	"\x06status\x18\x05 \x01(\v2\x15.guild.v1.AgentStatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x12AgentStreamRequest\x129\n" +
	"\amessage\x18\x01 \x01(\v2\x1d.guild.v1.AgentMessageRequestH\x00R\amessage\x123\n" +
	"\acontrol\x18\x02 \x01(\v2\x17.guild.v1.StreamControlH\x00R\acontrolB\t\n" +
	"\arequest\"\xbf\x01\n" +
	"\x13AgentStreamResponse\x12<\n" +
	"\bfragment\x18\x01 \x01(\v2\x1e.guild.v1.AgentMessageFragmentH\x00R\bfragment\x12/\n" +
	"\x06status\x18\x02 \x01(\v2\x15.guild.v1.AgentStatusH\x00R\x06status\x12-\n" +
	"\x05event\x18\x03 \x01(\v2\x15.guild.v1.StreamEventH\x00R\x05eventB\n" +
	"\n" +
	"\bresponse\"\x91\x02\n" +
	"\x14AgentMessageFragment\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vis_complete\x18\x03 \x01(\bR\n" +
	"isComplete\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12H\n" +
	"\bmetadata\x18\x05 \x03(\v2,.guild.v1.AgentMessageFragment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\rStreamControl\x129\n" +
	"\acommand\x18\x01 \x01(\x0e2\x1f.guild.v1.StreamControl.CommandR\acommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"5\n" +
	"\aCommand\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\t\n" +
	"\x05PAUSE\x10\x02\x12\n" +
	"\n" +
	"\x06RESUME\x10\x03\"\x86\x04\n" +
	"\vStreamEvent\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.guild.v1.StreamEvent.EventTypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.guild.v1.StreamEvent.DataEntryR\x04data\x12>\n" +
	"\x0etool_execution\x18\x04 \x01(\v2\x17.guild.v1.ToolExecutionR\rtoolExecution\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\tEventType\x12\x12\n" +
	"\x0eAGENT_THINKING\x10\x00\x12\x11\n" +
	"\rAGENT_WORKING\x10\x01\x12\x12\n" +
	"\x0eTOOL_EXECUTING\x10\x02\x12\x15\n" +
	"\x11MEMORY_RETRIEVING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\x12\n" +
	"\x0eTOOL_DISCOVERY\x10\x05\x12\x18\n" +
	"\x14TOOL_EXECUTION_START\x10\x06\x12\x1b\n" +
	"\x17TOOL_EXECUTION_PROGRESS\x10\a\x12\x1b\n" +
	"\x17TOOL_EXECUTION_COMPLETE\x10\b\x12\x1f\n" +
	"\x1bTOOL_AUTHORIZATION_REQUIRED\x10\t\"\xcb\x03\n" +
	"\rToolExecution\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12G\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2'.guild.v1.ToolExecution.ParametersEntryR\n" +
	"parameters\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\t \x01(\x03R\vcompletedAt\x12%\n" +
	"\x0eestimated_cost\x18\n" +
	" \x01(\x01R\restimatedCost\x121\n" +
	"\x14required_permissions\x18\v \x03(\tR\x13requiredPermissions\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x11ListAgentsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12%\n" +
	"\x0einclude_status\x18\x02 \x01(\bR\rincludeStatus\"b\n" +
	"\x12ListAgentsResponse\x12+\n" +
	"\x06agents\x18\x01 \x03(\v2\x13.guild.v1.AgentInfoR\x06agents\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x92\x02\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12-\n" +
	"\x06status\x18\x05 \x01(\v2\x15.guild.v1.AgentStatusR\x06status\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.guild.v1.AgentInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x15GetAgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\"\xd9\x02\n" +
	"\vAgentStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.guild.v1.AgentStatus.StateR\x05state\x12!\n" +
	"\fcurrent_task\x18\x02 \x01(\tR\vcurrentTask\x12#\n" +
	"\rlast_activity\x18\x03 \x01(\x03R\flastActivity\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.guild.v1.AgentStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x05State\x12\b\n" +
	"\x04IDLE\x10\x00\x12\f\n" +
	"\bTHINKING\x10\x01\x12\v\n" +
	"\aWORKING\x10\x02\x12\v\n" +
	"\aWAITING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\v\n" +
	"\aOFFLINE\x10\x052\xa9\v\n" +
	"\x05Guild\x12@\n" +
	"\rWatchCampaign\x12\x16.guild.v1.WatchRequest\x1a\x15.guild.v1.BoardUpdate0\x01\x12?\n" +
	"\vGetCampaign\x12\x1c.guild.v1.GetCampaignRequest\x1a\x12.guild.v1.Campaign\x12P\n" +
	"\rListCampaigns\x12\x1e.guild.v1.ListCampaignsRequest\x1a\x1f.guild.v1.ListCampaignsResponse\x12E\n" +
	"\x0eCreateCampaign\x12\x1f.guild.v1.CreateCampaignRequest\x1a\x12.guild.v1.Campaign\x12E\n" +
	"\x0eUpdateCampaign\x12\x1f.guild.v1.UpdateCampaignRequest\x1a\x12.guild.v1.Campaign\x12S\n" +
	"\x0eDeleteCampaign\x12\x1f.guild.v1.DeleteCampaignRequest\x1a .guild.v1.DeleteCampaignResponse\x12L\n" +
	"\x15StartPlanningCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12H\n" +
	"\x11MarkCampaignReady\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12D\n" +
	"\rStartCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12D\n" +
	"\rPauseCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12E\n" +
	"\x0eResumeCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12G\n" +
	"\x10CompleteCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12E\n" +
	"\x0eCancelCampaign\x12\x1f.guild.v1.CampaignActionRequest\x1a\x12.guild.v1.Campaign\x12K\n" +
	"\x16AddObjectiveToCampaign\x12\x1d.guild.v1.AddObjectiveRequest\x1a\x12.guild.v1.Campaign\x12S\n" +
	"\x1bRemoveObjectiveFromCampaign\x12 .guild.v1.RemoveObjectiveRequest\x1a\x12.guild.v1.Campaign\x12S\n" +
	"\x12SendMessageToAgent\x12\x1d.guild.v1.AgentMessageRequest\x1a\x1e.guild.v1.AgentMessageResponse\x12Z\n" +
	"\x17StreamAgentConversation\x12\x1c.guild.v1.AgentStreamRequest\x1a\x1d.guild.v1.AgentStreamResponse(\x010\x01\x12P\n" +
	"\x13ListAvailableAgents\x12\x1b.guild.v1.ListAgentsRequest\x1a\x1c.guild.v1.ListAgentsResponse\x12H\n" +
	"\x0eGetAgentStatus\x12\x1f.guild.v1.GetAgentStatusRequest\x1a\x15.guild.v1.AgentStatusB2Z0github.com/guild-ventures/guild-core/internal/grpc/pbb\x06proto3"

var (
	file_guild_v1_guild_proto_rawDescOnce sync.Once
	file_guild_v1_guild_proto_rawDescData []byte
)

func file_guild_v1_guild_proto_rawDescGZIP() []byte {
	file_guild_v1_guild_proto_rawDescOnce.Do(func() {
		file_guild_v1_guild_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_v1_guild_proto_rawDesc), len(file_guild_v1_guild_proto_rawDesc)))
	})
	return file_guild_v1_guild_proto_rawDescData
}

var file_guild_v1_guild_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_guild_v1_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_guild_v1_guild_proto_goTypes = []any{
	(StreamControl_Command)(0),     // 0: guild.v1.StreamControl.Command
	(StreamEvent_EventType)(0),     // 1: guild.v1.StreamEvent.EventType
	(AgentStatus_State)(0),         // 2: guild.v1.AgentStatus.State
	(*Campaign)(nil),               // 3: guild.v1.Campaign
	(*WatchRequest)(nil),           // 4: guild.v1.WatchRequest
	(*BoardUpdate)(nil),            // 5: guild.v1.BoardUpdate
	(*BoardMetadata)(nil),          // 6: guild.v1.BoardMetadata
	(*GetCampaignRequest)(nil),     // 7: guild.v1.GetCampaignRequest
	(*ListCampaignsRequest)(nil),   // 8: guild.v1.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),  // 9: guild.v1.ListCampaignsResponse
	(*CreateCampaignRequest)(nil),  // 10: guild.v1.CreateCampaignRequest
	(*UpdateCampaignRequest)(nil),  // 11: guild.v1.UpdateCampaignRequest
	(*DeleteCampaignRequest)(nil),  // 12: guild.v1.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil), // 13: guild.v1.DeleteCampaignResponse
	(*CampaignActionRequest)(nil),  // 14: guild.v1.CampaignActionRequest
	(*AddObjectiveRequest)(nil),    // 15: guild.v1.AddObjectiveRequest
	(*RemoveObjectiveRequest)(nil), // 16: guild.v1.RemoveObjectiveRequest
	(*ErrorDetail)(nil),            // 17: guild.v1.ErrorDetail
	(*AgentMessageRequest)(nil),    // 18: guild.v1.AgentMessageRequest
	(*AgentMessageResponse)(nil),   // 19: guild.v1.AgentMessageResponse
	(*AgentStreamRequest)(nil),     // 20: guild.v1.AgentStreamRequest
	(*AgentStreamResponse)(nil),    // 21: guild.v1.AgentStreamResponse
	(*AgentMessageFragment)(nil),   // 22: guild.v1.AgentMessageFragment
	(*StreamControl)(nil),          // 23: guild.v1.StreamControl
	(*StreamEvent)(nil),            // 24: guild.v1.StreamEvent
	(*ToolExecution)(nil),          // 25: guild.v1.ToolExecution
	(*ListAgentsRequest)(nil),      // 26: guild.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),     // 27: guild.v1.ListAgentsResponse
	(*AgentInfo)(nil),              // 28: guild.v1.AgentInfo
	(*GetAgentStatusRequest)(nil),  // 29: guild.v1.GetAgentStatusRequest
	(*AgentStatus)(nil),            // 30: guild.v1.AgentStatus
	nil,                            // 31: guild.v1.Campaign.MetadataEntry
	nil,                            // 32: guild.v1.CreateCampaignRequest.MetadataEntry
	nil,                            // 33: guild.v1.UpdateCampaignRequest.MetadataEntry
	nil,                            // 34: guild.v1.ErrorDetail.MetadataEntry
	nil,                            // 35: guild.v1.AgentMessageRequest.ContextEntry
	nil,                            // 36: guild.v1.AgentMessageResponse.MetadataEntry
	nil,                            // 37: guild.v1.AgentMessageFragment.MetadataEntry
	nil,                            // 38: guild.v1.StreamEvent.DataEntry
	nil,                            // 39: guild.v1.ToolExecution.ParametersEntry
	nil,                            // 40: guild.v1.AgentInfo.MetadataEntry
	nil,                            // 41: guild.v1.AgentStatus.MetadataEntry
}
var file_guild_v1_guild_proto_depIdxs = []int32{
	31, // 0: guild.v1.Campaign.metadata:type_name -> guild.v1.Campaign.MetadataEntry
	6,  // 1: guild.v1.BoardUpdate.metadata:type_name -> guild.v1.BoardMetadata
	3,  // 2: guild.v1.ListCampaignsResponse.campaigns:type_name -> guild.v1.Campaign
	32, // 3: guild.v1.CreateCampaignRequest.metadata:type_name -> guild.v1.CreateCampaignRequest.MetadataEntry
	33, // 4: guild.v1.UpdateCampaignRequest.metadata:type_name -> guild.v1.UpdateCampaignRequest.MetadataEntry
	34, // 5: guild.v1.ErrorDetail.metadata:type_name -> guild.v1.ErrorDetail.MetadataEntry
	35, // 6: guild.v1.AgentMessageRequest.context:type_name -> guild.v1.AgentMessageRequest.ContextEntry
	36, // 7: guild.v1.AgentMessageResponse.metadata:type_name -> guild.v1.AgentMessageResponse.MetadataEntry
	30, // 8: guild.v1.AgentMessageResponse.status:type_name -> guild.v1.AgentStatus
	18, // 9: guild.v1.AgentStreamRequest.message:type_name -> guild.v1.AgentMessageRequest
	23, // 10: guild.v1.AgentStreamRequest.control:type_name -> guild.v1.StreamControl
	22, // 11: guild.v1.AgentStreamResponse.fragment:type_name -> guild.v1.AgentMessageFragment
	30, // 12: guild.v1.AgentStreamResponse.status:type_name -> guild.v1.AgentStatus
	24, // 13: guild.v1.AgentStreamResponse.event:type_name -> guild.v1.StreamEvent
	37, // 14: guild.v1.AgentMessageFragment.metadata:type_name -> guild.v1.AgentMessageFragment.MetadataEntry
	0,  // 15: guild.v1.StreamControl.command:type_name -> guild.v1.StreamControl.Command
	1,  // 16: guild.v1.StreamEvent.type:type_name -> guild.v1.StreamEvent.EventType
	38, // 17: guild.v1.StreamEvent.data:type_name -> guild.v1.StreamEvent.DataEntry
	25, // 18: guild.v1.StreamEvent.tool_execution:type_name -> guild.v1.ToolExecution
	39, // 19: guild.v1.ToolExecution.parameters:type_name -> guild.v1.ToolExecution.ParametersEntry
	28, // 20: guild.v1.ListAgentsResponse.agents:type_name -> guild.v1.AgentInfo
	30, // 21: guild.v1.AgentInfo.status:type_name -> guild.v1.AgentStatus
	40, // 22: guild.v1.AgentInfo.metadata:type_name -> guild.v1.AgentInfo.MetadataEntry
	2,  // 23: guild.v1.AgentStatus.state:type_name -> guild.v1.AgentStatus.State
	41, // 24: guild.v1.AgentStatus.metadata:type_name -> guild.v1.AgentStatus.MetadataEntry
	4,  // 25: guild.v1.Guild.WatchCampaign:input_type -> guild.v1.WatchRequest
	7,  // 26: guild.v1.Guild.GetCampaign:input_type -> guild.v1.GetCampaignRequest
	8,  // 27: guild.v1.Guild.ListCampaigns:input_type -> guild.v1.ListCampaignsRequest
	10, // 28: guild.v1.Guild.CreateCampaign:input_type -> guild.v1.CreateCampaignRequest
	11, // 29: guild.v1.Guild.UpdateCampaign:input_type -> guild.v1.UpdateCampaignRequest
	12, // 30: guild.v1.Guild.DeleteCampaign:input_type -> guild.v1.DeleteCampaignRequest
	14, // 31: guild.v1.Guild.StartPlanningCampaign:input_type -> guild.v1.CampaignActionRequest
	14, // 32: guild.v1.Guild.MarkCampaignReady:input_type -> guild.v1.CampaignActionRequest
	14, // 33: guild.v1.Guild.StartCampaign:input_type -> guild.v1.CampaignActionRequest
	14, // 34: guild.v1.Guild.PauseCampaign:input_type -> guild.v1.CampaignActionRequest
	14, // 35: guild.v1.Guild.ResumeCampaign:input_type -> guild.v1.CampaignActionRequest
	14, // 36: guild.v1.Guild.CompleteCampaign:input_type -> guild.v1.CampaignActionRequest
	14, // 37: guild.v1.Guild.CancelCampaign:input_type -> guild.v1.CampaignActionRequest
	15, // 38: guild.v1.Guild.AddObjectiveToCampaign:input_type -> guild.v1.AddObjectiveRequest
	16, // 39: guild.v1.Guild.RemoveObjectiveFromCampaign:input_type -> guild.v1.RemoveObjectiveRequest
	18, // 40: guild.v1.Guild.SendMessageToAgent:input_type -> guild.v1.AgentMessageRequest
	20, // 41: guild.v1.Guild.StreamAgentConversation:input_type -> guild.v1.AgentStreamRequest
	26, // 42: guild.v1.Guild.ListAvailableAgents:input_type -> guild.v1.ListAgentsRequest
	29, // 43: guild.v1.Guild.GetAgentStatus:input_type -> guild.v1.GetAgentStatusRequest
	5,  // 44: guild.v1.Guild.WatchCampaign:output_type -> guild.v1.BoardUpdate
	3,  // 45: guild.v1.Guild.GetCampaign:output_type -> guild.v1.Campaign
	9,  // 46: guild.v1.Guild.ListCampaigns:output_type -> guild.v1.ListCampaignsResponse
	3,  // 47: guild.v1.Guild.CreateCampaign:output_type -> guild.v1.Campaign
	3,  // 48: guild.v1.Guild.UpdateCampaign:output_type -> guild.v1.Campaign
	13, // 49: guild.v1.Guild.DeleteCampaign:output_type -> guild.v1.DeleteCampaignResponse
	3,  // 50: guild.v1.Guild.StartPlanningCampaign:output_type -> guild.v1.Campaign
	3,  // 51: guild.v1.Guild.MarkCampaignReady:output_type -> guild.v1.Campaign
	3,  // 52: guild.v1.Guild.StartCampaign:output_type -> guild.v1.Campaign
	3,  // 53: guild.v1.Guild.PauseCampaign:output_type -> guild.v1.Campaign
	3,  // 54: guild.v1.Guild.ResumeCampaign:output_type -> guild.v1.Campaign
	3,  // 55: guild.v1.Guild.CompleteCampaign:output_type -> guild.v1.Campaign
	3,  // 56: guild.v1.Guild.CancelCampaign:output_type -> guild.v1.Campaign
	3,  // 57: guild.v1.Guild.AddObjectiveToCampaign:output_type -> guild.v1.Campaign
	3,  // 58: guild.v1.Guild.RemoveObjectiveFromCampaign:output_type -> guild.v1.Campaign
	19, // 59: guild.v1.Guild.SendMessageToAgent:output_type -> guild.v1.AgentMessageResponse
	21, // 60: guild.v1.Guild.StreamAgentConversation:output_type -> guild.v1.AgentStreamResponse
	27, // 61: guild.v1.Guild.ListAvailableAgents:output_type -> guild.v1.ListAgentsResponse
	30, // 62: guild.v1.Guild.GetAgentStatus:output_type -> guild.v1.AgentStatus
	44, // [44:63] is the sub-list for method output_type
	25, // [25:44] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_guild_v1_guild_proto_init() }
func file_guild_v1_guild_proto_init() {
	if File_guild_v1_guild_proto != nil {
		return
	}
	file_guild_v1_guild_proto_msgTypes[17].OneofWrappers = []any{
		(*AgentStreamRequest_Message)(nil),
		(*AgentStreamRequest_Control)(nil),
	}
	file_guild_v1_guild_proto_msgTypes[18].OneofWrappers = []any{
		(*AgentStreamResponse_Fragment)(nil),
		(*AgentStreamResponse_Status)(nil),
		(*AgentStreamResponse_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_v1_guild_proto_rawDesc), len(file_guild_v1_guild_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guild_v1_guild_proto_goTypes,
		DependencyIndexes: file_guild_v1_guild_proto_depIdxs,
		EnumInfos:         file_guild_v1_guild_proto_enumTypes,
		MessageInfos:      file_guild_v1_guild_proto_msgTypes,
	}.Build()
	File_guild_v1_guild_proto = out.File
	file_guild_v1_guild_proto_goTypes = nil
	file_guild_v1_guild_proto_depIdxs = nil
}
