// Copyright (C) 2025 SWS Industries LLC (DBA Blockhead Consulting)
// SPDX-License-Identifier: LicenseRef-ANGRY-GOAT-0.2

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package db

import (
	"context"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, type, provider, model, capabilities, tools, cost_magnitude)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Provider      *string     `json:"provider"`
	Model         *string     `json:"model"`
	Capabilities  interface{} `json:"capabilities"`
	Tools         interface{} `json:"tools"`
	CostMagnitude *int64      `json:"cost_magnitude"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Provider,
		arg.Model,
		arg.Capabilities,
		arg.Tools,
		arg.CostMagnitude,
	)
	return err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, type, provider, model, capabilities, tools, cost_magnitude, created_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Provider,
		&i.Model,
		&i.Capabilities,
		&i.Tools,
		&i.CostMagnitude,
		&i.CreatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, type, provider, model, capabilities, tools, cost_magnitude, created_at FROM agents ORDER BY created_at DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Provider,
			&i.Model,
			&i.Capabilities,
			&i.Tools,
			&i.CostMagnitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByType = `-- name: ListAgentsByType :many
SELECT id, name, type, provider, model, capabilities, tools, cost_magnitude, created_at FROM agents WHERE type = ? ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByType(ctx context.Context, type_ string) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Provider,
			&i.Model,
			&i.Capabilities,
			&i.Tools,
			&i.CostMagnitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE agents
SET name = ?, type = ?, provider = ?, model = ?, capabilities = ?, tools = ?, cost_magnitude = ?
WHERE id = ?
`

type UpdateAgentParams struct {
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Provider      *string     `json:"provider"`
	Model         *string     `json:"model"`
	Capabilities  interface{} `json:"capabilities"`
	Tools         interface{} `json:"tools"`
	CostMagnitude *int64      `json:"cost_magnitude"`
	ID            string      `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.ExecContext(ctx, updateAgent,
		arg.Name,
		arg.Type,
		arg.Provider,
		arg.Model,
		arg.Capabilities,
		arg.Tools,
		arg.CostMagnitude,
		arg.ID,
	)
	return err
}
