// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chat_sessions.sql

package db

import (
	"context"
	"time"
)

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM chat_messages WHERE session_id = ?
`

func (q *Queries) CountMessages(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM chat_sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBookmark = `-- name: CreateBookmark :exec
INSERT INTO session_bookmarks (id, session_id, message_id, name)
VALUES (?, ?, ?, ?)
`

type CreateBookmarkParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	MessageID string `json:"message_id"`
	Name      string `json:"name"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, createBookmark,
		arg.ID,
		arg.SessionID,
		arg.MessageID,
		arg.Name,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO chat_messages (id, session_id, role, content, tool_calls, metadata)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID        string      `json:"id"`
	SessionID string      `json:"session_id"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	ToolCalls interface{} `json:"tool_calls"`
	Metadata  interface{} `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.Metadata,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO chat_sessions (id, name, campaign_id, metadata)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	CampaignID *string     `json:"campaign_id"`
	Metadata   interface{} `json:"metadata"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.CampaignID,
		arg.Metadata,
	)
	return err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM session_bookmarks WHERE id = ?
`

func (q *Queries) DeleteBookmark(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM chat_messages WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM chat_sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getBookmark = `-- name: GetBookmark :one
SELECT id, session_id, message_id, name, created_at FROM session_bookmarks WHERE id = ?
`

func (q *Queries) GetBookmark(ctx context.Context, id string) (SessionBookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmark, id)
	var i SessionBookmark
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getBookmarks = `-- name: GetBookmarks :many
SELECT b.id, b.session_id, b.message_id, b.name, b.created_at, m.content as message_content, m.role
FROM session_bookmarks b
JOIN chat_messages m ON b.message_id = m.id
WHERE b.session_id = ?
ORDER BY b.created_at DESC
`

type GetBookmarksRow struct {
	ID             string     `json:"id"`
	SessionID      string     `json:"session_id"`
	MessageID      string     `json:"message_id"`
	Name           string     `json:"name"`
	CreatedAt      *time.Time `json:"created_at"`
	MessageContent string     `json:"message_content"`
	Role           string     `json:"role"`
}

func (q *Queries) GetBookmarks(ctx context.Context, sessionID string) ([]GetBookmarksRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookmarksRow{}
	for rows.Next() {
		var i GetBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.Name,
			&i.CreatedAt,
			&i.MessageContent,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksByMessage = `-- name: GetBookmarksByMessage :many
SELECT id, session_id, message_id, name, created_at FROM session_bookmarks WHERE message_id = ?
`

func (q *Queries) GetBookmarksByMessage(ctx context.Context, messageID string) ([]SessionBookmark, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarksByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionBookmark{}
	for rows.Next() {
		var i SessionBookmark
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, content, created_at, tool_calls, metadata FROM chat_messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.ToolCalls,
		&i.Metadata,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, session_id, role, content, created_at, tool_calls, metadata FROM chat_messages
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetMessages(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ToolCalls,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesAfter = `-- name: GetMessagesAfter :many
SELECT id, session_id, role, content, created_at, tool_calls, metadata FROM chat_messages
WHERE session_id = ? AND created_at > ?
ORDER BY created_at ASC
`

type GetMessagesAfterParams struct {
	SessionID string     `json:"session_id"`
	CreatedAt *time.Time `json:"created_at"`
}

func (q *Queries) GetMessagesAfter(ctx context.Context, arg GetMessagesAfterParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesAfter, arg.SessionID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ToolCalls,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesPaginated = `-- name: GetMessagesPaginated :many
SELECT id, session_id, role, content, created_at, tool_calls, metadata FROM chat_messages
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetMessagesPaginatedParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) GetMessagesPaginated(ctx context.Context, arg GetMessagesPaginatedParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesPaginated, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ToolCalls,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, name, campaign_id, created_at, updated_at, metadata FROM chat_sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CampaignID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, name, campaign_id, created_at, updated_at, metadata FROM chat_sessions 
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListSessionsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CampaignID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByCampaign = `-- name: ListSessionsByCampaign :many
SELECT id, name, campaign_id, created_at, updated_at, metadata FROM chat_sessions 
WHERE campaign_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByCampaign(ctx context.Context, campaignID *string) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CampaignID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.session_id, m.role, m.content, m.created_at, m.tool_calls, m.metadata, s.name as session_name, s.campaign_id
FROM chat_messages m
JOIN chat_sessions s ON m.session_id = s.id
WHERE m.content LIKE ?
ORDER BY m.created_at DESC
LIMIT ? OFFSET ?
`

type SearchMessagesParams struct {
	Content string `json:"content"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

type SearchMessagesRow struct {
	ID          string      `json:"id"`
	SessionID   string      `json:"session_id"`
	Role        string      `json:"role"`
	Content     string      `json:"content"`
	CreatedAt   *time.Time  `json:"created_at"`
	ToolCalls   interface{} `json:"tool_calls"`
	Metadata    interface{} `json:"metadata"`
	SessionName string      `json:"session_name"`
	CampaignID  *string     `json:"campaign_id"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages, arg.Content, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ToolCalls,
			&i.Metadata,
			&i.SessionName,
			&i.CampaignID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessions = `-- name: SearchSessions :many
SELECT id, name, campaign_id, created_at, updated_at, metadata FROM chat_sessions
WHERE name LIKE ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type SearchSessionsParams struct {
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, searchSessions, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CampaignID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE chat_sessions
SET name = ?, metadata = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSessionParams struct {
	Name     string      `json:"name"`
	Metadata interface{} `json:"metadata"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.Name, arg.Metadata, arg.ID)
	return err
}
