// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Agent struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Provider      *string     `json:"provider"`
	Model         *string     `json:"model"`
	Capabilities  interface{} `json:"capabilities"`
	Tools         interface{} `json:"tools"`
	CostMagnitude *int64      `json:"cost_magnitude"`
	CreatedAt     *time.Time  `json:"created_at"`
}

type Board struct {
	ID           string     `json:"id"`
	CommissionID string     `json:"commission_id"`
	Name         string     `json:"name"`
	Description  *string    `json:"description"`
	Status       string     `json:"status"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type Campaign struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Status    string     `json:"status"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Commission struct {
	ID          string      `json:"id"`
	CampaignID  string      `json:"campaign_id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Domain      *string     `json:"domain"`
	Context     interface{} `json:"context"`
	Status      string      `json:"status"`
	CreatedAt   *time.Time  `json:"created_at"`
}

type PromptChain struct {
	ID        string     `json:"id"`
	AgentID   string     `json:"agent_id"`
	TaskID    *string    `json:"task_id"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type PromptChainMessage struct {
	ID         int64      `json:"id"`
	ChainID    string     `json:"chain_id"`
	Role       string     `json:"role"`
	Content    string     `json:"content"`
	Name       *string    `json:"name"`
	Timestamp  *time.Time `json:"timestamp"`
	TokenUsage *int64     `json:"token_usage"`
}

type Task struct {
	ID              string      `json:"id"`
	CommissionID    string      `json:"commission_id"`
	AssignedAgentID *string     `json:"assigned_agent_id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	Status          string      `json:"status"`
	Column          string      `json:"column"`
	StoryPoints     *int64      `json:"story_points"`
	Metadata        interface{} `json:"metadata"`
	CreatedAt       *time.Time  `json:"created_at"`
	UpdatedAt       *time.Time  `json:"updated_at"`
	BoardID         *string     `json:"board_id"`
}

type TaskEvent struct {
	ID        int64      `json:"id"`
	TaskID    string     `json:"task_id"`
	AgentID   *string    `json:"agent_id"`
	EventType string     `json:"event_type"`
	OldValue  *string    `json:"old_value"`
	NewValue  *string    `json:"new_value"`
	Reason    *string    `json:"reason"`
	CreatedAt *time.Time `json:"created_at"`
}
