// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Agent struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Provider      *string     `json:"provider"`
	Model         *string     `json:"model"`
	Capabilities  interface{} `json:"capabilities"`
	Tools         interface{} `json:"tools"`
	CostMagnitude *int64      `json:"cost_magnitude"`
	CreatedAt     *time.Time  `json:"created_at"`
}

type Board struct {
	ID           string     `json:"id"`
	CommissionID string     `json:"commission_id"`
	Name         string     `json:"name"`
	Description  *string    `json:"description"`
	Status       string     `json:"status"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type Campaign struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Status    string     `json:"status"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type ChatMessage struct {
	ID        string      `json:"id"`
	SessionID string      `json:"session_id"`
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	CreatedAt *time.Time  `json:"created_at"`
	ToolCalls interface{} `json:"tool_calls"`
	Metadata  interface{} `json:"metadata"`
}

type ChatSession struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	CampaignID *string     `json:"campaign_id"`
	CreatedAt  *time.Time  `json:"created_at"`
	UpdatedAt  *time.Time  `json:"updated_at"`
	Metadata   interface{} `json:"metadata"`
}

type Commission struct {
	ID          string      `json:"id"`
	CampaignID  string      `json:"campaign_id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Domain      *string     `json:"domain"`
	Context     interface{} `json:"context"`
	Status      string      `json:"status"`
	CreatedAt   *time.Time  `json:"created_at"`
}

type MemoryStore struct {
	Bucket    string     `json:"bucket"`
	Key       string     `json:"key"`
	Value     []byte     `json:"value"`
	CreatedAt *time.Time `json:"created_at"`
}

type PromptChain struct {
	ID        string     `json:"id"`
	AgentID   string     `json:"agent_id"`
	TaskID    *string    `json:"task_id"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type PromptChainMessage struct {
	ID         int64      `json:"id"`
	ChainID    string     `json:"chain_id"`
	Role       string     `json:"role"`
	Content    string     `json:"content"`
	Name       *string    `json:"name"`
	Timestamp  *time.Time `json:"timestamp"`
	TokenUsage *int64     `json:"token_usage"`
}

type SessionBookmark struct {
	ID        string     `json:"id"`
	SessionID string     `json:"session_id"`
	MessageID string     `json:"message_id"`
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
}

type Task struct {
	ID              string      `json:"id"`
	CommissionID    string      `json:"commission_id"`
	BoardID         *string     `json:"board_id"`
	AssignedAgentID *string     `json:"assigned_agent_id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	Status          string      `json:"status"`
	Column          string      `json:"column"`
	StoryPoints     *int64      `json:"story_points"`
	Metadata        interface{} `json:"metadata"`
	CreatedAt       *time.Time  `json:"created_at"`
	UpdatedAt       *time.Time  `json:"updated_at"`
}

type TaskEvent struct {
	ID        int64      `json:"id"`
	TaskID    string     `json:"task_id"`
	AgentID   *string    `json:"agent_id"`
	EventType string     `json:"event_type"`
	OldValue  *string    `json:"old_value"`
	NewValue  *string    `json:"new_value"`
	Reason    *string    `json:"reason"`
	CreatedAt *time.Time `json:"created_at"`
}

type Template struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Category    string     `json:"category"`
	Content     string     `json:"content"`
	Language    *string    `json:"language"`
	UseCount    *int64     `json:"use_count"`
	IsBuiltIn   *bool      `json:"is_built_in"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type TemplateCategory struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Icon        *string    `json:"icon"`
	SortOrder   *int64     `json:"sort_order"`
	CreatedAt   *time.Time `json:"created_at"`
}

type TemplateUsage struct {
	ID            string      `json:"id"`
	TemplateID    string      `json:"template_id"`
	CampaignID    *string     `json:"campaign_id"`
	UsedAt        *time.Time  `json:"used_at"`
	VariablesUsed interface{} `json:"variables_used"`
	Context       *string     `json:"context"`
}

type TemplateVariable struct {
	ID           string      `json:"id"`
	TemplateID   string      `json:"template_id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	DefaultValue *string     `json:"default_value"`
	Required     *bool       `json:"required"`
	VariableType *string     `json:"variable_type"`
	Options      interface{} `json:"options"`
	CreatedAt    *time.Time  `json:"created_at"`
}
