// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: prompt_chains.sql

package db

import (
	"context"
	"time"
)

const addPromptChainMessage = `-- name: AddPromptChainMessage :exec
INSERT INTO prompt_chain_messages (chain_id, role, content, name, timestamp, token_usage)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddPromptChainMessageParams struct {
	ChainID    string     `json:"chain_id"`
	Role       string     `json:"role"`
	Content    string     `json:"content"`
	Name       *string    `json:"name"`
	Timestamp  *time.Time `json:"timestamp"`
	TokenUsage *int64     `json:"token_usage"`
}

func (q *Queries) AddPromptChainMessage(ctx context.Context, arg AddPromptChainMessageParams) error {
	_, err := q.db.ExecContext(ctx, addPromptChainMessage,
		arg.ChainID,
		arg.Role,
		arg.Content,
		arg.Name,
		arg.Timestamp,
		arg.TokenUsage,
	)
	return err
}

const createPromptChain = `-- name: CreatePromptChain :exec
INSERT INTO prompt_chains (id, agent_id, task_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePromptChainParams struct {
	ID        string     `json:"id"`
	AgentID   string     `json:"agent_id"`
	TaskID    *string    `json:"task_id"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) CreatePromptChain(ctx context.Context, arg CreatePromptChainParams) error {
	_, err := q.db.ExecContext(ctx, createPromptChain,
		arg.ID,
		arg.AgentID,
		arg.TaskID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePromptChain = `-- name: DeletePromptChain :exec
DELETE FROM prompt_chains
WHERE id = ?
`

func (q *Queries) DeletePromptChain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePromptChain, id)
	return err
}

const deletePromptChainMessages = `-- name: DeletePromptChainMessages :exec
DELETE FROM prompt_chain_messages
WHERE chain_id = ?
`

func (q *Queries) DeletePromptChainMessages(ctx context.Context, chainID string) error {
	_, err := q.db.ExecContext(ctx, deletePromptChainMessages, chainID)
	return err
}

const getPromptChain = `-- name: GetPromptChain :one
SELECT id, agent_id, task_id, created_at, updated_at
FROM prompt_chains
WHERE id = ?
`

func (q *Queries) GetPromptChain(ctx context.Context, id string) (PromptChain, error) {
	row := q.db.QueryRowContext(ctx, getPromptChain, id)
	var i PromptChain
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptChainMessages = `-- name: GetPromptChainMessages :many
SELECT id, chain_id, role, content, name, timestamp, token_usage
FROM prompt_chain_messages
WHERE chain_id = ?
ORDER BY timestamp ASC
`

func (q *Queries) GetPromptChainMessages(ctx context.Context, chainID string) ([]PromptChainMessage, error) {
	rows, err := q.db.QueryContext(ctx, getPromptChainMessages, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptChainMessage{}
	for rows.Next() {
		var i PromptChainMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.Role,
			&i.Content,
			&i.Name,
			&i.Timestamp,
			&i.TokenUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptChainMessagesWithLimit = `-- name: GetPromptChainMessagesWithLimit :many
SELECT id, chain_id, role, content, name, timestamp, token_usage
FROM prompt_chain_messages
WHERE chain_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type GetPromptChainMessagesWithLimitParams struct {
	ChainID string `json:"chain_id"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) GetPromptChainMessagesWithLimit(ctx context.Context, arg GetPromptChainMessagesWithLimitParams) ([]PromptChainMessage, error) {
	rows, err := q.db.QueryContext(ctx, getPromptChainMessagesWithLimit, arg.ChainID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptChainMessage{}
	for rows.Next() {
		var i PromptChainMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.Role,
			&i.Content,
			&i.Name,
			&i.Timestamp,
			&i.TokenUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptChainsByAgent = `-- name: GetPromptChainsByAgent :many
SELECT id, agent_id, task_id, created_at, updated_at
FROM prompt_chains
WHERE agent_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetPromptChainsByAgent(ctx context.Context, agentID string) ([]PromptChain, error) {
	rows, err := q.db.QueryContext(ctx, getPromptChainsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptChain{}
	for rows.Next() {
		var i PromptChain
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptChainsByTask = `-- name: GetPromptChainsByTask :many
SELECT id, agent_id, task_id, created_at, updated_at
FROM prompt_chains
WHERE task_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetPromptChainsByTask(ctx context.Context, taskID *string) ([]PromptChain, error) {
	rows, err := q.db.QueryContext(ctx, getPromptChainsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptChain{}
	for rows.Next() {
		var i PromptChain
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
