// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddPromptChainMessage(ctx context.Context, arg AddPromptChainMessageParams) error
	AssignTaskToAgent(ctx context.Context, arg AssignTaskToAgentParams) error
	CountMessages(ctx context.Context, sessionID string) (int64, error)
	CountSessions(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) error
	CreateBoard(ctx context.Context, arg CreateBoardParams) error
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) error
	CreateCommission(ctx context.Context, arg CreateCommissionParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreatePromptChain(ctx context.Context, arg CreatePromptChainParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	// Template management queries for SQLC generation
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	// Template Categories queries
	CreateTemplateCategory(ctx context.Context, arg CreateTemplateCategoryParams) (TemplateCategory, error)
	// Template Usage tracking queries
	CreateTemplateUsage(ctx context.Context, arg CreateTemplateUsageParams) (TemplateUsage, error)
	// Template Variables queries
	CreateTemplateVariable(ctx context.Context, arg CreateTemplateVariableParams) (TemplateVariable, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteBoard(ctx context.Context, id string) error
	DeleteBookmark(ctx context.Context, id string) error
	DeleteCampaign(ctx context.Context, id string) error
	DeleteCommission(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeletePromptChain(ctx context.Context, id string) error
	DeletePromptChainMessages(ctx context.Context, chainID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id string) error
	DeleteTaskEvents(ctx context.Context, taskID string) error
	DeleteTemplate(ctx context.Context, id string) error
	DeleteTemplateCategory(ctx context.Context, id string) error
	DeleteTemplateVariable(ctx context.Context, id string) error
	DeleteTemplateVariablesByTemplate(ctx context.Context, templateID string) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetAgentWorkload(ctx context.Context) ([]GetAgentWorkloadRow, error)
	GetBoard(ctx context.Context, id string) (Board, error)
	GetBoardByCommission(ctx context.Context, commissionID string) (Board, error)
	GetBookmark(ctx context.Context, id string) (SessionBookmark, error)
	GetBookmarks(ctx context.Context, sessionID string) ([]GetBookmarksRow, error)
	GetBookmarksByMessage(ctx context.Context, messageID string) ([]SessionBookmark, error)
	GetCampaign(ctx context.Context, id string) (Campaign, error)
	GetCommission(ctx context.Context, id string) (Commission, error)
	GetMessage(ctx context.Context, id string) (ChatMessage, error)
	GetMessages(ctx context.Context, sessionID string) ([]ChatMessage, error)
	GetMessagesAfter(ctx context.Context, arg GetMessagesAfterParams) ([]ChatMessage, error)
	GetMessagesPaginated(ctx context.Context, arg GetMessagesPaginatedParams) ([]ChatMessage, error)
	GetMostUsedTemplates(ctx context.Context, limit int64) ([]GetMostUsedTemplatesRow, error)
	GetPromptChain(ctx context.Context, id string) (PromptChain, error)
	GetPromptChainMessages(ctx context.Context, chainID string) ([]PromptChainMessage, error)
	GetPromptChainMessagesWithLimit(ctx context.Context, arg GetPromptChainMessagesWithLimitParams) ([]PromptChainMessage, error)
	GetPromptChainsByAgent(ctx context.Context, agentID string) ([]PromptChain, error)
	GetPromptChainsByTask(ctx context.Context, taskID *string) ([]PromptChain, error)
	GetSession(ctx context.Context, id string) (ChatSession, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTaskHistory(ctx context.Context, taskID string) ([]TaskEvent, error)
	GetTemplate(ctx context.Context, id string) (Template, error)
	GetTemplateByName(ctx context.Context, name string) (Template, error)
	GetTemplateCategory(ctx context.Context, id string) (TemplateCategory, error)
	GetTemplateStats(ctx context.Context) (GetTemplateStatsRow, error)
	GetTemplateUsageCount(ctx context.Context, id string) (*int64, error)
	GetTemplateUsageHistory(ctx context.Context, arg GetTemplateUsageHistoryParams) ([]GetTemplateUsageHistoryRow, error)
	GetTemplateVariables(ctx context.Context, templateID string) ([]TemplateVariable, error)
	// Combined queries for efficient data fetching
	GetTemplateWithVariables(ctx context.Context, id string) ([]GetTemplateWithVariablesRow, error)
	IncrementTemplateUsage(ctx context.Context, id string) error
	ListAgents(ctx context.Context) ([]Agent, error)
	ListAgentsByType(ctx context.Context, type_ string) ([]Agent, error)
	ListBoards(ctx context.Context) ([]Board, error)
	ListCampaigns(ctx context.Context) ([]Campaign, error)
	ListCommissions(ctx context.Context) ([]Commission, error)
	ListCommissionsByCampaign(ctx context.Context, campaignID string) ([]Commission, error)
	ListCommissionsByDomain(ctx context.Context, domain *string) ([]Commission, error)
	ListCommissionsByStatus(ctx context.Context, status string) ([]Commission, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]ChatSession, error)
	ListSessionsByCampaign(ctx context.Context, campaignID *string) ([]ChatSession, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByBoard(ctx context.Context, boardID *string) ([]Task, error)
	ListTasksByCommission(ctx context.Context, commissionID string) ([]Task, error)
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	ListTasksForKanban(ctx context.Context, boardID *string) ([]ListTasksForKanbanRow, error)
	ListTemplateCategories(ctx context.Context) ([]TemplateCategory, error)
	ListTemplates(ctx context.Context) ([]Template, error)
	ListTemplatesByCategory(ctx context.Context, category string) ([]Template, error)
	RecordTaskEvent(ctx context.Context, arg RecordTaskEventParams) error
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]ChatSession, error)
	SearchTemplates(ctx context.Context, dollar_1 *string) ([]Template, error)
	SetCommissionCompleted(ctx context.Context, id string) error
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) error
	UpdateBoard(ctx context.Context, arg UpdateBoardParams) error
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error
	UpdateCommission(ctx context.Context, arg UpdateCommissionParams) error
	UpdateCommissionStatus(ctx context.Context, arg UpdateCommissionStatusParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskColumn(ctx context.Context, arg UpdateTaskColumnParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error)
	UpdateTemplateCategory(ctx context.Context, arg UpdateTemplateCategoryParams) (TemplateCategory, error)
	UpdateTemplateVariable(ctx context.Context, arg UpdateTemplateVariableParams) (TemplateVariable, error)
}

var _ Querier = (*Queries)(nil)
