// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package db

import (
	"context"
	"time"
)

const assignTaskToAgent = `-- name: AssignTaskToAgent :exec
UPDATE tasks 
SET assigned_agent_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type AssignTaskToAgentParams struct {
	AssignedAgentID *string `json:"assigned_agent_id"`
	ID              string  `json:"id"`
}

func (q *Queries) AssignTaskToAgent(ctx context.Context, arg AssignTaskToAgentParams) error {
	_, err := q.db.ExecContext(ctx, assignTaskToAgent, arg.AssignedAgentID, arg.ID)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, commission_id, title, description, status, column, story_points, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID           string      `json:"id"`
	CommissionID string      `json:"commission_id"`
	Title        string      `json:"title"`
	Description  *string     `json:"description"`
	Status       string      `json:"status"`
	Column       string      `json:"column"`
	StoryPoints  *int64      `json:"story_points"`
	Metadata     interface{} `json:"metadata"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.CommissionID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Column,
		arg.StoryPoints,
		arg.Metadata,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getAgentWorkload = `-- name: GetAgentWorkload :many
SELECT 
    a.id,
    a.name,
    COUNT(t.id) as task_count,
    SUM(CASE WHEN t.status = 'in_progress' THEN 1 ELSE 0 END) as active_tasks
FROM agents a
LEFT JOIN tasks t ON a.id = t.assigned_agent_id
GROUP BY a.id, a.name
`

type GetAgentWorkloadRow struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	TaskCount   int64    `json:"task_count"`
	ActiveTasks *float64 `json:"active_tasks"`
}

func (q *Queries) GetAgentWorkload(ctx context.Context) ([]GetAgentWorkloadRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentWorkload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentWorkloadRow{}
	for rows.Next() {
		var i GetAgentWorkloadRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TaskCount,
			&i.ActiveTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, commission_id, assigned_agent_id, title, description, status, "column", story_points, metadata, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CommissionID,
		&i.AssignedAgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Column,
		&i.StoryPoints,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskHistory = `-- name: GetTaskHistory :many
SELECT id, task_id, agent_id, event_type, old_value, new_value, reason, created_at FROM task_events 
WHERE task_id = ? 
ORDER BY created_at DESC
`

func (q *Queries) GetTaskHistory(ctx context.Context, taskID string) ([]TaskEvent, error) {
	rows, err := q.db.QueryContext(ctx, getTaskHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AgentID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, commission_id, assigned_agent_id, title, description, status, "column", story_points, metadata, created_at, updated_at FROM tasks ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CommissionID,
			&i.AssignedAgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Column,
			&i.StoryPoints,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCommission = `-- name: ListTasksByCommission :many
SELECT id, commission_id, assigned_agent_id, title, description, status, "column", story_points, metadata, created_at, updated_at FROM tasks WHERE commission_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTasksByCommission(ctx context.Context, commissionID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByCommission, commissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CommissionID,
			&i.AssignedAgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Column,
			&i.StoryPoints,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, commission_id, assigned_agent_id, title, description, status, "column", story_points, metadata, created_at, updated_at FROM tasks WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CommissionID,
			&i.AssignedAgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Column,
			&i.StoryPoints,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForKanban = `-- name: ListTasksForKanban :many
SELECT 
    t.id, t.commission_id, t.assigned_agent_id, t.title, t.description, t.status, t."column", t.story_points, t.metadata, t.created_at, t.updated_at,
    a.name as agent_name,
    a.type as agent_type
FROM tasks t
LEFT JOIN agents a ON t.assigned_agent_id = a.id
WHERE t.commission_id = ?
ORDER BY t.column, t.created_at
`

type ListTasksForKanbanRow struct {
	ID              string      `json:"id"`
	CommissionID    string      `json:"commission_id"`
	AssignedAgentID *string     `json:"assigned_agent_id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	Status          string      `json:"status"`
	Column          string      `json:"column"`
	StoryPoints     *int64      `json:"story_points"`
	Metadata        interface{} `json:"metadata"`
	CreatedAt       *time.Time  `json:"created_at"`
	UpdatedAt       *time.Time  `json:"updated_at"`
	AgentName       *string     `json:"agent_name"`
	AgentType       *string     `json:"agent_type"`
}

func (q *Queries) ListTasksForKanban(ctx context.Context, commissionID string) ([]ListTasksForKanbanRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksForKanban, commissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksForKanbanRow{}
	for rows.Next() {
		var i ListTasksForKanbanRow
		if err := rows.Scan(
			&i.ID,
			&i.CommissionID,
			&i.AssignedAgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Column,
			&i.StoryPoints,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentName,
			&i.AgentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTaskEvent = `-- name: RecordTaskEvent :exec
INSERT INTO task_events (task_id, agent_id, event_type, old_value, new_value, reason)
VALUES (?, ?, ?, ?, ?, ?)
`

type RecordTaskEventParams struct {
	TaskID    string  `json:"task_id"`
	AgentID   *string `json:"agent_id"`
	EventType string  `json:"event_type"`
	OldValue  *string `json:"old_value"`
	NewValue  *string `json:"new_value"`
	Reason    *string `json:"reason"`
}

func (q *Queries) RecordTaskEvent(ctx context.Context, arg RecordTaskEventParams) error {
	_, err := q.db.ExecContext(ctx, recordTaskEvent,
		arg.TaskID,
		arg.AgentID,
		arg.EventType,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET title = ?, description = ?, status = ?, column = ?, story_points = ?, metadata = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTaskParams struct {
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Status      string      `json:"status"`
	Column      string      `json:"column"`
	StoryPoints *int64      `json:"story_points"`
	Metadata    interface{} `json:"metadata"`
	ID          string      `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Column,
		arg.StoryPoints,
		arg.Metadata,
		arg.ID,
	)
	return err
}

const updateTaskColumn = `-- name: UpdateTaskColumn :exec
UPDATE tasks 
SET column = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTaskColumnParams struct {
	Column string `json:"column"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskColumn(ctx context.Context, arg UpdateTaskColumnParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskColumn, arg.Column, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks 
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
