// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: templates.sql

package db

import (
	"context"
	"time"
)

const createTemplate = `-- name: CreateTemplate :one

INSERT INTO templates (
    id, name, description, category, content, language, is_built_in
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at
`

type CreateTemplateParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Category    string  `json:"category"`
	Content     string  `json:"content"`
	Language    *string `json:"language"`
	IsBuiltIn   *bool   `json:"is_built_in"`
}

// Template management queries for SQLC generation
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Language,
		arg.IsBuiltIn,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Language,
		&i.UseCount,
		&i.IsBuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateCategory = `-- name: CreateTemplateCategory :one

INSERT INTO template_categories (
    id, name, description, icon, sort_order
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, name, description, icon, sort_order, created_at
`

type CreateTemplateCategoryParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Icon        *string `json:"icon"`
	SortOrder   *int64  `json:"sort_order"`
}

// Template Categories queries
func (q *Queries) CreateTemplateCategory(ctx context.Context, arg CreateTemplateCategoryParams) (TemplateCategory, error) {
	row := q.db.QueryRowContext(ctx, createTemplateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.SortOrder,
	)
	var i TemplateCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createTemplateUsage = `-- name: CreateTemplateUsage :one

INSERT INTO template_usage (
    id, template_id, campaign_id, variables_used, context
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, template_id, campaign_id, used_at, variables_used, context
`

type CreateTemplateUsageParams struct {
	ID            string      `json:"id"`
	TemplateID    string      `json:"template_id"`
	CampaignID    *string     `json:"campaign_id"`
	VariablesUsed interface{} `json:"variables_used"`
	Context       *string     `json:"context"`
}

// Template Usage tracking queries
func (q *Queries) CreateTemplateUsage(ctx context.Context, arg CreateTemplateUsageParams) (TemplateUsage, error) {
	row := q.db.QueryRowContext(ctx, createTemplateUsage,
		arg.ID,
		arg.TemplateID,
		arg.CampaignID,
		arg.VariablesUsed,
		arg.Context,
	)
	var i TemplateUsage
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.CampaignID,
		&i.UsedAt,
		&i.VariablesUsed,
		&i.Context,
	)
	return i, err
}

const createTemplateVariable = `-- name: CreateTemplateVariable :one

INSERT INTO template_variables (
    id, template_id, name, description, default_value, required, variable_type, options
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, template_id, name, description, default_value, required, variable_type, options, created_at
`

type CreateTemplateVariableParams struct {
	ID           string      `json:"id"`
	TemplateID   string      `json:"template_id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	DefaultValue *string     `json:"default_value"`
	Required     *bool       `json:"required"`
	VariableType *string     `json:"variable_type"`
	Options      interface{} `json:"options"`
}

// Template Variables queries
func (q *Queries) CreateTemplateVariable(ctx context.Context, arg CreateTemplateVariableParams) (TemplateVariable, error) {
	row := q.db.QueryRowContext(ctx, createTemplateVariable,
		arg.ID,
		arg.TemplateID,
		arg.Name,
		arg.Description,
		arg.DefaultValue,
		arg.Required,
		arg.VariableType,
		arg.Options,
	)
	var i TemplateVariable
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.DefaultValue,
		&i.Required,
		&i.VariableType,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates 
WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const deleteTemplateCategory = `-- name: DeleteTemplateCategory :exec
DELETE FROM template_categories 
WHERE id = ?
`

func (q *Queries) DeleteTemplateCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateCategory, id)
	return err
}

const deleteTemplateVariable = `-- name: DeleteTemplateVariable :exec
DELETE FROM template_variables 
WHERE id = ?
`

func (q *Queries) DeleteTemplateVariable(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateVariable, id)
	return err
}

const deleteTemplateVariablesByTemplate = `-- name: DeleteTemplateVariablesByTemplate :exec
DELETE FROM template_variables 
WHERE template_id = ?
`

func (q *Queries) DeleteTemplateVariablesByTemplate(ctx context.Context, templateID string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateVariablesByTemplate, templateID)
	return err
}

const getMostUsedTemplates = `-- name: GetMostUsedTemplates :many
SELECT t.id, t.name, t.description, t.category, t.content, t.language, t.use_count, t.is_built_in, t.created_at, t.updated_at, COUNT(tu.id) as recent_usage_count
FROM templates t
LEFT JOIN template_usage tu ON t.id = tu.template_id 
    AND tu.used_at > datetime('now', '-30 days')
GROUP BY t.id
ORDER BY recent_usage_count DESC, t.use_count DESC
LIMIT ?
`

type GetMostUsedTemplatesRow struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	Description      *string    `json:"description"`
	Category         string     `json:"category"`
	Content          string     `json:"content"`
	Language         *string    `json:"language"`
	UseCount         *int64     `json:"use_count"`
	IsBuiltIn        *bool      `json:"is_built_in"`
	CreatedAt        *time.Time `json:"created_at"`
	UpdatedAt        *time.Time `json:"updated_at"`
	RecentUsageCount int64      `json:"recent_usage_count"`
}

func (q *Queries) GetMostUsedTemplates(ctx context.Context, limit int64) ([]GetMostUsedTemplatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMostUsedTemplates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMostUsedTemplatesRow{}
	for rows.Next() {
		var i GetMostUsedTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Language,
			&i.UseCount,
			&i.IsBuiltIn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecentUsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at FROM templates 
WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Language,
		&i.UseCount,
		&i.IsBuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at FROM templates 
WHERE name = ?
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Language,
		&i.UseCount,
		&i.IsBuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateCategory = `-- name: GetTemplateCategory :one
SELECT id, name, description, icon, sort_order, created_at FROM template_categories 
WHERE id = ?
`

func (q *Queries) GetTemplateCategory(ctx context.Context, id string) (TemplateCategory, error) {
	row := q.db.QueryRowContext(ctx, getTemplateCategory, id)
	var i TemplateCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateStats = `-- name: GetTemplateStats :one
SELECT 
    COUNT(*) as total_templates,
    COUNT(DISTINCT category) as total_categories,
    AVG(use_count) as avg_use_count,
    MAX(use_count) as max_use_count
FROM templates
`

type GetTemplateStatsRow struct {
	TotalTemplates  int64       `json:"total_templates"`
	TotalCategories int64       `json:"total_categories"`
	AvgUseCount     *float64    `json:"avg_use_count"`
	MaxUseCount     interface{} `json:"max_use_count"`
}

func (q *Queries) GetTemplateStats(ctx context.Context) (GetTemplateStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTemplateStats)
	var i GetTemplateStatsRow
	err := row.Scan(
		&i.TotalTemplates,
		&i.TotalCategories,
		&i.AvgUseCount,
		&i.MaxUseCount,
	)
	return i, err
}

const getTemplateUsageCount = `-- name: GetTemplateUsageCount :one
SELECT use_count FROM templates 
WHERE id = ?
`

func (q *Queries) GetTemplateUsageCount(ctx context.Context, id string) (*int64, error) {
	row := q.db.QueryRowContext(ctx, getTemplateUsageCount, id)
	var use_count *int64
	err := row.Scan(&use_count)
	return use_count, err
}

const getTemplateUsageHistory = `-- name: GetTemplateUsageHistory :many
SELECT tu.id, tu.template_id, tu.campaign_id, tu.used_at, tu.variables_used, tu.context, t.name as template_name 
FROM template_usage tu
JOIN templates t ON tu.template_id = t.id
WHERE tu.campaign_id = ?
ORDER BY tu.used_at DESC
LIMIT ?
`

type GetTemplateUsageHistoryParams struct {
	CampaignID *string `json:"campaign_id"`
	Limit      int64   `json:"limit"`
}

type GetTemplateUsageHistoryRow struct {
	ID            string      `json:"id"`
	TemplateID    string      `json:"template_id"`
	CampaignID    *string     `json:"campaign_id"`
	UsedAt        *time.Time  `json:"used_at"`
	VariablesUsed interface{} `json:"variables_used"`
	Context       *string     `json:"context"`
	TemplateName  string      `json:"template_name"`
}

func (q *Queries) GetTemplateUsageHistory(ctx context.Context, arg GetTemplateUsageHistoryParams) ([]GetTemplateUsageHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateUsageHistory, arg.CampaignID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplateUsageHistoryRow{}
	for rows.Next() {
		var i GetTemplateUsageHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.CampaignID,
			&i.UsedAt,
			&i.VariablesUsed,
			&i.Context,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateVariables = `-- name: GetTemplateVariables :many
SELECT id, template_id, name, description, default_value, required, variable_type, options, created_at FROM template_variables 
WHERE template_id = ?
ORDER BY name ASC
`

func (q *Queries) GetTemplateVariables(ctx context.Context, templateID string) ([]TemplateVariable, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateVariables, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateVariable{}
	for rows.Next() {
		var i TemplateVariable
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Description,
			&i.DefaultValue,
			&i.Required,
			&i.VariableType,
			&i.Options,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateWithVariables = `-- name: GetTemplateWithVariables :many

SELECT 
    t.id as template_id,
    t.name as template_name,
    t.description as template_description,
    t.category as template_category,
    t.content as template_content,
    t.language as template_language,
    t.use_count as template_use_count,
    t.is_built_in as template_is_built_in,
    t.created_at as template_created_at,
    t.updated_at as template_updated_at,
    tv.id as variable_id,
    tv.name as variable_name,
    tv.description as variable_description,
    tv.default_value as variable_default_value,
    tv.required as variable_required,
    tv.variable_type as variable_type,
    tv.options as variable_options
FROM templates t
LEFT JOIN template_variables tv ON t.id = tv.template_id
WHERE t.id = ?
ORDER BY tv.name ASC
`

type GetTemplateWithVariablesRow struct {
	TemplateID           string      `json:"template_id"`
	TemplateName         string      `json:"template_name"`
	TemplateDescription  *string     `json:"template_description"`
	TemplateCategory     string      `json:"template_category"`
	TemplateContent      string      `json:"template_content"`
	TemplateLanguage     *string     `json:"template_language"`
	TemplateUseCount     *int64      `json:"template_use_count"`
	TemplateIsBuiltIn    *bool       `json:"template_is_built_in"`
	TemplateCreatedAt    *time.Time  `json:"template_created_at"`
	TemplateUpdatedAt    *time.Time  `json:"template_updated_at"`
	VariableID           *string     `json:"variable_id"`
	VariableName         *string     `json:"variable_name"`
	VariableDescription  *string     `json:"variable_description"`
	VariableDefaultValue *string     `json:"variable_default_value"`
	VariableRequired     *bool       `json:"variable_required"`
	VariableType         *string     `json:"variable_type"`
	VariableOptions      interface{} `json:"variable_options"`
}

// Combined queries for efficient data fetching
func (q *Queries) GetTemplateWithVariables(ctx context.Context, id string) ([]GetTemplateWithVariablesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateWithVariables, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplateWithVariablesRow{}
	for rows.Next() {
		var i GetTemplateWithVariablesRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.TemplateName,
			&i.TemplateDescription,
			&i.TemplateCategory,
			&i.TemplateContent,
			&i.TemplateLanguage,
			&i.TemplateUseCount,
			&i.TemplateIsBuiltIn,
			&i.TemplateCreatedAt,
			&i.TemplateUpdatedAt,
			&i.VariableID,
			&i.VariableName,
			&i.VariableDescription,
			&i.VariableDefaultValue,
			&i.VariableRequired,
			&i.VariableType,
			&i.VariableOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTemplateUsage = `-- name: IncrementTemplateUsage :exec
UPDATE templates 
SET use_count = use_count + 1 
WHERE id = ?
`

func (q *Queries) IncrementTemplateUsage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementTemplateUsage, id)
	return err
}

const listTemplateCategories = `-- name: ListTemplateCategories :many
SELECT id, name, description, icon, sort_order, created_at FROM template_categories 
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListTemplateCategories(ctx context.Context) ([]TemplateCategory, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateCategory{}
	for rows.Next() {
		var i TemplateCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at FROM templates 
ORDER BY use_count DESC, name ASC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Language,
			&i.UseCount,
			&i.IsBuiltIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByCategory = `-- name: ListTemplatesByCategory :many
SELECT id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at FROM templates 
WHERE category = ?
ORDER BY use_count DESC, name ASC
`

func (q *Queries) ListTemplatesByCategory(ctx context.Context, category string) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Language,
			&i.UseCount,
			&i.IsBuiltIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTemplates = `-- name: SearchTemplates :many
SELECT id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at FROM templates 
WHERE name LIKE '%' || ?1 || '%' 
   OR description LIKE '%' || ?1 || '%' 
   OR content LIKE '%' || ?1 || '%'
ORDER BY use_count DESC, name ASC
`

func (q *Queries) SearchTemplates(ctx context.Context, dollar_1 *string) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, searchTemplates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Language,
			&i.UseCount,
			&i.IsBuiltIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates 
SET name = ?, description = ?, category = ?, content = ?, language = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, category, content, language, use_count, is_built_in, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Category    string  `json:"category"`
	Content     string  `json:"content"`
	Language    *string `json:"language"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Language,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Language,
		&i.UseCount,
		&i.IsBuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplateCategory = `-- name: UpdateTemplateCategory :one
UPDATE template_categories 
SET name = ?, description = ?, icon = ?, sort_order = ?
WHERE id = ?
RETURNING id, name, description, icon, sort_order, created_at
`

type UpdateTemplateCategoryParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Icon        *string `json:"icon"`
	SortOrder   *int64  `json:"sort_order"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateTemplateCategory(ctx context.Context, arg UpdateTemplateCategoryParams) (TemplateCategory, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateCategory,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.SortOrder,
		arg.ID,
	)
	var i TemplateCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateTemplateVariable = `-- name: UpdateTemplateVariable :one
UPDATE template_variables 
SET name = ?, description = ?, default_value = ?, required = ?, variable_type = ?, options = ?
WHERE id = ?
RETURNING id, template_id, name, description, default_value, required, variable_type, options, created_at
`

type UpdateTemplateVariableParams struct {
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	DefaultValue *string     `json:"default_value"`
	Required     *bool       `json:"required"`
	VariableType *string     `json:"variable_type"`
	Options      interface{} `json:"options"`
	ID           string      `json:"id"`
}

func (q *Queries) UpdateTemplateVariable(ctx context.Context, arg UpdateTemplateVariableParams) (TemplateVariable, error) {
	row := q.db.QueryRowContext(ctx, updateTemplateVariable,
		arg.Name,
		arg.Description,
		arg.DefaultValue,
		arg.Required,
		arg.VariableType,
		arg.Options,
		arg.ID,
	)
	var i TemplateVariable
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Description,
		&i.DefaultValue,
		&i.Required,
		&i.VariableType,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}
